<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("questions/save") ?>
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Create Question</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-7 col-md-7 col-xs-12 no-padding">
                        <div class="form-group-sm col-md-6 col-sm-12">
                            <label for="title">Title</label>
                            <?php echo $this->tag->textField(array("title", "size" => 30, 'class' => 'form-control','placeholder' => 'Enter title')) ?>
                        </div>
                        <div class="form-group-sm col-md-6 col-sm-12">
                            <label for="name">Type</label>
                            <?php echo $this->tag->textField(array("type", "size" => 30, 'class' => 'form-control','disabled'=>'disabled')) ?>
                        </div>
                        <div class="form-group col-md-12 col-sm-12">
                            <label for="name">Description</label>
                            <?php echo $this->tag->textArea(array("description", 'This is the content of the text-area', "rows"=>10, 'class' => 'form-control')) ?>
                        </div>
                        <div class="form-group-sm col-md-6 col-sm-12">
                            <label for="name">Active</label>
                            <?php echo $this->tag->selectStatic(array("active", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                        </div>
                        <div class="form-group col-md-6 col-sm-12">
                            <label for="translate">Translate</label>
                            <div class="input-group ">
                                <span class="input-group-addon">Click <input type="checkbox" class="minimal-red" name="translate" id="translate"> to translate</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-xs-12">
                        <div class="box box-solid">
                            <div class="box-header">
                                <h3 class="box-title">Questions & Answers</h3>
                            </div>
                            <div class="box-body">
                                <div id="question_answer">
                                    <?php $this->partial('questions/types/text'); ?>
                                </div>
                            </div>
                            <div class="box-footer text-right">
                                <div class="btn-group-xs">
                                    <button type="button" onclick="return addmore();" class="btn btn-small btn-info"><i class="fa fa-plus"></i> | Add Question & Answer</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12" id="question_translate" style="display: none">
                        <div class="header_title">Translate Question</div>
                        <div class="row">
                            <div class="col-lg-7 col-md-7 col-xs-12 no-padding">
                                <div class="form-group col-md-12 col-sm-12">
                                    <label for="name">Description</label>
                                    <?php echo $this->tag->textArea(array("translate_description", 'This is the content of the text-area', "rows"=>10, 'class' => 'form-control')) ?>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-xs-12">
                                <div class="box box-solid">
                                    <div class="box-header">
                                        <h3 class="box-title">Questions & Answers</h3>
                                    </div>
                                    <div class="box-body">
                                        <div id="question_answer">
                                            <?php $this->partial('questions/types/text'); ?>
                                        </div>
                                    </div>
                                    <div class="box-footer text-right">
                                        <div class="btn-group-xs">
                                            <button type="button" onclick="return addmore();" class="btn btn-small btn-info"><i class="fa fa-plus"></i> | Add Question & Answer</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <button type="button" onclick="return bookTool.cancelSaveQuestion(this);" class="btn btn-small btn-default"><i class="fa fa-refresh"></i> | Cancel</button>
                    <button type="button" onclick="return bookTool.saveQuestion(this);" class="btn btn-small btn-primary"><i class="fa fa-save"></i> | Save</button>
                </div>
            </div>
        </div>
    </div>
<?php echo $this->tag->endForm() ?>
<script>
    $(function(){
        $('#description').ckeditor();
        $('#translate_description').ckeditor();
        $("input[type='checkbox']:not(.simple), input[type='radio']:not(.simple)").iCheck({
            checkboxClass: 'icheckbox_minimal',
            radioClass: 'iradio_minimal',
            handle: 'checkbox'
        });
        $('#translate').on('ifChecked', function(event){
            //alert(event.type + ' callback');
            $('#question_translate').fadeIn();
        });
        $('#translate').on('ifUnchecked', function(event){
            //alert(event.type + ' callback');
            $('#question_translate').fadeOut();
        });

    });
</script>