<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<form action="#" method="post" id="question_form">
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title"><?php echo $this->tag->getValue('id')==''?$t->_('Create Question'):$t->_('Edit Question')?></h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-xs-12 no-padding">
                        <div class="form-group col-md-12 col-sm-12">
                            <label for="question"><?php echo $t->_('Question content')?></label>
                            <?php echo $this->tag->textArea(array("question", "rows"=>6, 'class' => 'form-control')) ?>
                        </div>
                        <div class="col-xs-12 no-padding">
                            <div class="form-group-sm col-xs-5">
                                <label for="status"><?php echo $t->_('Status')?></label>
                                <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                            </div>
                            <div class="form-group-sm col-xs-2 no-padding">
                                <label for="order"><?php echo $t->_('Order')?></label>
                                <div class="input-group input-group-sm col-xs-12">
                                    <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                                    <span class="input-group-addon">
                                    <i class="fa fa-sort-numeric-desc"></i>
                                </span>
                                </div>
                            </div>
                            <div class="form-group col-xs-5">
                                <label for="allow_translate"><?php echo $t->_('Question translate')?></label>
                                <div class="input-group ">
                                    <span class="input-group-addon"><i class="fa fa-text-width"></i> Click <?php echo $this->tag->checkField(array("allow_translate", $question->allow_translate?'checked':'')) ?> to translate</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="correct_msg"><?php echo $t->_('Correct Msg')?></label>
                            <?php echo $this->tag->textArea(array("correct_msg", "rows"=>1, 'class' => 'form-control')) ?>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="incorrect_msg"><?php echo $t->_('InCorrect Msg')?></label>
                            <?php echo $this->tag->textArea(array("incorrect_msg", "rows"=>1, 'class' => 'form-control')) ?>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-xs-12">
                        <div class="box box-solid">
                            <div class="box-header">
                                <div class="box-title">
                                    <?php echo $t->_('Answers')?>
                                    <div class="box-tools pull-right col-xs-4 no-padding">
                                        <div class="input-group pull-right">
                                            <span class="input-group-addon"><i class="fa fa-qrcode"></i> <?php echo $t->_('Question group')?></span>
                                            <span class="input-group-addon">
                                                <?php echo $this->tag->checkField(array("allow_translate", $question->allow_translate?'checked':'')) ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="box-body">
                                <div id="question_answer">
                                    <?php $this->partial('questions/types/'.strtolower($type), array('answers' => $question->answers)); ?>
                                </div>
                            </div>
                            <div class="box-footer text-right">
                                <div class="btn-group-xs">
                                    <button type="button" onclick="return addmore();" class="btn btn-small btn-info"><i class="fa fa-plus"></i> | <?php echo $t->_('Add more answer')?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 col-sm-12" id="question_translate_content" style="display: <?php echo $question->allow_translate?'block':'none'; ?>">
                        <div class="header_title"><?php echo $t->_('Question translate')?></div>
                        <div class="row">
                            <div class="col-lg-7 col-md-7 col-xs-12 no-padding">
                                <div class="form-group col-md-12 col-sm-12">
                                    <label for="question_translate"><?php echo $t->_('Question content (Translate)')?></label>
                                    <?php echo $this->tag->textArea(array("translates[question]","value"=>$question->translates['question'], "id"=>"translates_question", "rows"=>10, 'class' => 'form-control')) ?>
                                </div>
                            </div>
                            <div class="col-lg-5 col-md-5 col-xs-12">
                                <div class="box box-solid">
                                    <div class="box-header">
                                        <h3 class="box-title"><?php echo $t->_('Answers')?></h3>
                                    </div>
                                    <div class="box-body">
                                        <div id="translate_question_answer">
                                            <?php $this->partial('questions/types/'.strtolower($type).'_translate', array('answers' => $question->translates['answers'])); ?>
                                        </div>
                                    </div>
                                    <div class="box-footer text-right">
                                        <div class="btn-group-xs">
                                            <button type="button" onclick="return addTransMore();" class="btn btn-small btn-info"><i class="fa fa-plus"></i> | <?php echo $t->_('Add more answer')?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <?php echo $this->tag->hiddenField("section_id") ?>
            <?php echo $this->tag->hiddenField("type") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <button type="button" onclick="return bookTool.resetForm(this,'question');" class="btn btn-small btn-warning"><i class="fa fa-refresh"></i> | <?php echo $t->_('Cancel')?></button>
                    <button type="button" onclick="return bookTool.saveQuestion(this);" class="btn btn-small btn-primary"><i class="fa fa-save"></i> | <?php echo $t->_('Save')?></button>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    var question = CKEDITOR.replace('question');
    CKFinder.setupCKEditor( question, '/js/ckfinder/' );
    var question_translate = CKEDITOR.replace('translates_question');
    CKFinder.setupCKEditor( question_translate, '/js/ckfinder/' );
    question.on( 'change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#question').html(evt.editor.getData());
    });
    question_translate.on( 'change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#translates_question').html(evt.editor.getData());
    });
    var edit_answer = CKEDITOR.replace('edit_answer');

    $(function(){
        $("input[type='checkbox'], input[type='radio']").iCheck({
            checkboxClass: 'icheckbox_minimal',
            radioClass: 'iradio_minimal'
        });
        $('#allow_translate').on('ifChecked', function(event){
            //alert(event.type + ' callback');
            $('#question_translate_content').fadeIn();
        });
        $('#allow_translate').on('ifUnchecked', function(event){
            //alert(event.type + ' callback');
            $('#question_translate_content').fadeOut();
        });
    });

    var elementPopup = '';
    function openModal(myself) {
        elementPopup = $(myself).parent().parent().find('.modal_text');
        var value = elementPopup.val();
        $('#edit_answer').val(value);
        $('#mymodal').modal('show');
        edit_answer.setData(value);
    };
    function applyDataModal(myself) {
        elementPopup.val(edit_answer.getData());
        $('#mymodal').modal('hide');
    };
</script>
<div class="modal fade" id="mymodal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel"><?php echo $t->_('Edit Answer') ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->tag->textArea(array("edit_answer", "rows"=>10, 'class' => 'form-control')) ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $t->_('Cancel') ?></button>
                <button type="button" class="btn btn-primary" onclick="applyDataModal(this);"><?php echo $t->_('Apply') ?></button>
            </div>
        </div>
    </div>
</div>
