<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<form action="/questions/saveSummary" method="post" id="question_form">
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Tạo câu hỏi cho bài trắc nghiệm tổng hợp (<?php echo $section->name ?>)</h3>
            </div>
            <div class="box-body no-padding">
                <table class="table table-striped">
                    <tr>
                        <th>Loại câu hỏi</th>
                        <th class="text-right">Số câu hỏi hiện có</th>
                        <th class="text-right">Số câu hỏi lấy ngẫu nhiên</th>
                    </tr>
                    <?php foreach($sections as $section):?>
                        <tr>
                            <td colspan="3" class="bg-green"><?php echo $section->name ?></td>
                        </tr>
                        <?php foreach($questions[$section->getId()->{'$id'}] as $type => $quest):?>
                            <tr>
                                <td><span class="fa fa-ellipsis-h"></span> <?php echo $type ?></td>
                                <td class="text-right"><?php echo count($quest) ?></td>
                                <td class="text-right"><?php echo $this->tag->textField(array("number[$type]", "size" => "3")) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <?php echo $this->tag->hiddenField("section_id") ?>
            <?php echo $this->tag->hiddenField("chapter_id") ?>
            <?php echo $this->tag->hiddenField( array("questionIds",'value' => json_encode($questions))) ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <button type="button" onclick="return bookTool.resetForm(this,'question');" class="btn btn-small btn-warning"><i class="fa fa-refresh"></i> | Cancel</button>
                    <button type="submit" class="btn btn-small btn-primary"><i class="fa fa-save"></i> | Save</button>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(function(){
        /*$("#question_form").submit(function(ev) {
            $.ajax({
                url: '/questions/saveSummary',
                data:$('#question_form').serialize(),
                type: 'post',
                dataType: 'json',
                success: function(result) {
                    console.log(result);
                    if(result.error) {
                        alertify.error(result.msg);
                    } else {
                        alertify.success(result.msg);
                    }
                    //window.location.reload();
                },
                error: function(jqXHR){
                    alertify.error("Error: Loading data");
                }
            });
            ev.preventDefault();
            return false;
        });*/
    });
</script>