<div class="row pad">
    <div class="box-header">
        <div class="box-title">
            <?php echo $section->breadcrumb['book_name'] ?> > <?php echo $section->breadcrumb['chapter_name'] ?> > <?php echo $section->name ?> ><strong> Danh sách câu hỏi tổng hợp</strong>
            <div class="pull-right" style="margin-right: 5px">
                <div class="dropdown">
                    <button class="btn btn-xs btn-primary" type="button" onclick="return bookTool.editQuestion(this, '','SUMMARY');">
                        <i class="fa fa-plus"></i> | Tạo câu hỏi tổng hợp
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive" id="chapter_container">
    <!-- THE MESSAGES -->
    <table class="table table-mailbox table-bordered table-hover ">
        <tr class="unread">
            <td class="small-col"><input type="checkbox" name="checkAll"/></td>
            <td class="title">Name</td>
            <td style="max-width:20%" class="question">Question</td>
            <td class="text-right">Type</td>
            <td style="width: 15%" class="text-center">Action</td>
        </tr>
        <?php foreach($questions as $question):?>
            <tr class="">
                <td class="small-col"><input type="checkbox" /></td>
                <td class="title"><?php echo $question->name ?></td>
                <td ><?php echo Helper::limitString($question->question,50) ?></td>
                <td class="text-right"><?php echo $question->type ?></td>
                <td class="text-center">
                    <button class="btn btn-xs btn-warning" onclick="return bookTool.editQuestion(this, '<?php echo $question->getId() ?>');"><i class="fa fa-pencil"></i> | Edit</button>
                    <button class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> | Del</button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div><!-- /.table-responsive -->