<div class="row pad">
    <div class="box-header">
        <div class="box-title">
            <?php echo $section->breadcrumb['book_name'] ?> > <?php echo $section->breadcrumb['chapter_name'] ?> > <?php echo $section->name ?> ><strong> Danh sách câu hỏi</strong>
            <div class="nav navbar-nav navbar-right" style="margin-right: 5px">
                <div class="dropdown">
                    <button class="btn btn-xs btn-flat btn-primary dropdown-toggle" type="button" id="create_question" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <i class="fa fa-plus"></i> | <?php echo $t->_('Create question') ?>
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="create_question">
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','SINGLE');"><?php echo $t->_('Single Choice') ?></a></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','MULTI');"><?php echo $t->_('Multi Choice') ?></a></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','FREE_TEXT');"><?php echo $t->_('Free Text') ?></a></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','PLACE_ANSWER_IMAGE');"><?php echo $t->_('Place Answer Image') ?></a></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','PLACE_ANSWER_TEXT');"><?php echo $t->_('Place Answer Text') ?></a></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','SORT');"><?php echo $t->_('Sort') ?></a></li>
                        <li class="divider"></li>
                        <li><a style="cursor:pointer;" onclick="return bookTool.editQuestion(this, '','GROUP');"><?php echo $t->_('Question group') ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive" id="chapter_container">
    <!-- THE MESSAGES -->
    <table class="table table-mailbox table-bordered table-hover" id="sortable">
        <tr class="unread">
            <td class="text-center" style="width:10px">
                <div class="fa fa-save disabled" style="color:gray;" id="save_order" onclick="saveOrder(this);"></div>
            </td>
            <td  class="text-center small-col">STT</td>
            <td style="max-width:50%" class="question"><?php echo $t->_('Question content') ?></td>
            <td class="text-right"><?php echo $t->_('Question type') ?></td>
            <td style="width: 10%" class="text-center"><?php echo $t->_('Tools') ?></td>
        </tr>
        <?php foreach($questions as $question):?>
            <tr class="order" data-order="<?php echo $question->order ?>" data-id="<?php echo $question->getId() ?>">
                <td class="text-center" style="cursor:move"><i class="fa fa-ellipsis-v"></i><i class="fa fa-ellipsis-v"></i></td>
                <td class="small-col text-center"><?php echo $question->order ?></td>
                <td style="white-space:pre-wrap; max-width: 50%;"><span class="math"><?php echo Helper::limitString($question->question,300) ?></span></td>
                <td class="text-right"><?php echo $question->type ?></td>
                <td class="text-center">
                    <button class="btn btn-xs btn-flat btn-warning" onclick="return bookTool.editQuestion(this, '<?php echo $question->getId() ?>');"><i class="fa fa-pencil"></i></button>
                    <button class="btn btn-xs btn-flat btn-danger"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div><!-- /.table-responsive -->
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            processEscapes: true,
            skipStartupTypeset:true
        }
    });
</script>
<script src="/js/MathJax/MathJax.js?config=TeX-AMS_HTML-full" type="text/javascript"></script>
<script>
    var math = document.getElementById('chapter_container');
    MathJax.Hub.Queue(["Typeset",MathJax.Hub,math]);

    var questionIds;
    $(function(){
        $( "#sortable tbody" ).sortable({
            placeholder: "ui-state-highlight",
            axis: 'y',
            update: function (event, ui) {
                questionIds = $.map($(this).find('tr.order'),function(obj, index) {
                    return {
                        id: $(obj).data('id'),
                        order: parseInt(index+1)
                    };
                });
                $('#save_order').removeClass('disabled');
                $('#save_order').css({color:'#f4543c',cursor:'pointer'});
            }
        }).disableSelection();
    });
    function saveOrder(myself) {
        $.ajax({
            type: "POST",
            url: "/questions/saveQuestionOrder",
            data: {questionIds:questionIds},
            dataType: 'json',
            beforeSend: function () {
            },
            success: function (results) {
                if(results.error == true) {
                    alertify.error("Error: Save failed");
                } else {
                    alertify.success("Saved successfully.");
                }
                $('#save_order').addClass('disabled');
                $('#save_order').css({color:'gray',cursor:'normal'});
            },
            error: function () {
                $('#save_order').addClass('disabled');
                alertify.error("Error: Save failed");
            }
        });
    }
</script>