<?php echo $this->getContent() ?>
<div class="col-xs-12 no-padding">
    <div class="page-header text-right">
        <div class="btn-group-xs">
            <?php echo $this->tag->linkTo(array("admin/roles/new", "<i class='fa fa-plus'></i> | Tạo quyền người dùng", "class"=>"btn btn-small btn-primary btn-flat")); ?>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left">Tên quyền</th>
            <th class="text-center">Sách</th>
            <th class="text-center">Xuất bản</th>
            <th class="text-center">Menu</th>
            <th class="text-center">Người dùng</th>
            <th class="text-center" style="width:145px;">Công cụ</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($roles as $index => $role) { ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td class="text-left"><?php echo $role->name ?></td>
                <td class="text-center">
                    <?php if($role->allowBook):?>
                        <i class="fa fa-check-square-o"></i>
                    <?php else: ?>
                        <i class="fa fa-square-o"></i>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php if($role->allowPublished):?>
                        <i class="fa fa-check-square-o"></i>
                    <?php else: ?>
                        <i class="fa fa-square-o"></i>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php if($role->allowMenu):?>
                        <i class="fa fa-check-square-o"></i>
                    <?php else: ?>
                        <i class="fa fa-square-o"></i>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php if($role->allowUser):?>
                        <i class="fa fa-check-square-o"></i>
                    <?php else: ?>
                        <i class="fa fa-square-o"></i>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <div class="btn-group-xs">
                        <?php //if(!in_array($role->name,$ignoreArr)): ?>
                            <?php echo $this->tag->linkTo(array("admin/roles/edit/" . $role->getId(), 'Sửa | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning btn-flat')); ?>
                            <?php echo $this->tag->linkTo(array("admin/roles/delete/" . $role->getId(), 'Xóa | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger btn-flat')); ?>
                        <?php //endif; ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>