<?php echo $this->getContent() ?>
<div class="col-xs-12 no-padding">
    <div class="page-header text-right">
        <div class="btn-group-xs">
            <?php echo $this->tag->linkTo(array("admin/roles/new", "<i class='fa fa-plus-circle'></i> | Create", "class"=>"btn btn-small btn-primary btn-flat")); ?>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left">Name</th>
            <th class="text-center small-col">Active</th>
            <th class="text-center" style="width:145px;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $role) { ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td class="text-left"><?php echo $role->name ?></td>
                <td class="text-center">
                    <?php
                    if($role->active) {
                        echo '<label class="label label-success"><i class="fa fa-unlock"></i></label>';
                    } else {
                        echo '<label class="label label-danger"><i class="fa fa-lock"></i></label>';
                    }
                    ?>
                </td>
                <td class="text-center">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("admin/roles/edit/" . $role->getId(), 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning btn-flat')); ?>
                        <?php echo $this->tag->linkTo(array("admin/roles/delete/" . $role->getId(), 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger btn-flat')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"roles/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>