<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-credit-card"></i> Nạp tiền cho (<?php echo $user->name ?>)</h4>
</div>
<form action="#" method="post" id="creditform">
    <div class="modal-body">
        <div class="row">
            <div class="col-xs-4">
                <img src="/files/images/credit-card.jpg" class="img-responsive img-rounded img-thumbnail" id="image_thumb">
            </div>
            <div class="col-xs-8">
                <div class="col-xs-12 no-padding">
                    <label for="amount">Số tiền cần nạp</label>
                    <?php echo $this->tag->numericField(array('amount', "min" => "1", 'class' => 'form-control','required'=>true)) ?>
                </div>
                <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                    <label for="note">Ghi chú</label>
                    <?php echo $this->tag->textArea(array("note", "rows" => 5, 'class' => 'form-control','required'=>true)) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer clearfix">
        <button type="button" class="btn btn-xs btn-danger btn-flat" data-dismiss="modal"><i class="fa fa-times"></i> Hủy bỏ</button>
        <button type="submit" class="btn btn-xs btn-primary btn-flat"><i class="fa fa-save"></i> Đồng ý</button>
    </div>
</form>
<script>
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }

    $("#creditform").submit(function() {
        var note = $('[name="note"]').val();
        var amount = $('[name="amount"]').val();
        $.ajax({
            url: '/admin/users/credit/<?php echo $user->getId() ?>',
            data:{note:note, amount:amount},
            type: 'post',
            dataType: 'json',
            success: function(result) {
                console.log(result);
                if(result.error) {
                    alertify.error(result.msg);
                } else {
                    alertify.success(result.msg);
                    $( ".fade " ).removeClass( "in" );
                }
                //window.location.reload();
            },
            error: function(jqXHR){
                alertify.error("Error: Loading data");
            }
        });
        return false;
    });
</script>