<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>" placeholder="<?php echo $t->_('Enter name for search',array('name' => '(tên | email | phone)'))?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-primary btn-flat" type="submit"><?php echo $t->_('Search') ?></button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-xs">
                <?php echo $this->tag->linkTo(array("admin/users/new", "<i class='fa fa-plus'></i> | ".$t->_('Create user'), "class"=>"btn btn-primary btn-flat")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center small-col">#</th>
            <th  class="text-left"><?php echo $t->_('User name') ?></th>
            <th  class="text-left">Email</th>
            <th  class="text-right" width="10%"><?php echo $t->_('Phone number') ?></th>
            <th  class="text-center" width="5%"><?php echo $t->_('Avatar') ?></th>
            <th  class="text-center" width="5%"><?php echo $t->_('Status') ?></th>
            <th  class="text-center" width="30%"><?php echo $t->_('Books bought') ?></th>
            <th  class="text-right" width="10%"><?php echo $t->_('Total Amount') ?></th>
            <th  class="text-center" width="60px"><?php echo $t->_('Tools') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $user) { ?>
            <?php
            if($user->active) {
                $linkLock = '<label class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td>
                    <?php echo $this->tag->linkTo(array("admin/users/edit/" . $user->getId()->{'$id'}, $user->name)); ?>
                </td>
                <td><?php echo $user->email ?></td>
                <td class="text-right"><?php echo $user->phone ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $user->avatar ?>"/></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-left">
                    <span style="word-wrap: break-word; max-width:300px">
                        <?php echo $this->tag->linkTo(array("admin/users/books/" . $user->getId(),Helper::renderBookInUser($user->books, 200))) ?>
                    </span>
                </td>
                <td class="text-right">
                    <?php echo $this->tag->linkTo(array("admin/users/history/" . $user->getId(), Helper::formatCurrency($user->total))) ?>
                </td>
                <td class="text-center">
                    <div class="btn-group-xs btn-group-vertical">
                        <a class="btn btn-block btn-primary btn-flat" onclick="credit(this,'<?php echo $user->getId()?>');" data-toggle="modal" data-target="#user-modal">Credit or debit card</a>
                        <a class="btn btn-block btn-warning btn-flat" onclick="buythebook(this,'<?php echo $user->getId()?>');" data-toggle="modal" data-target="#user-modal">Buy the book</a>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<div class="modal fade" id="user-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" id="user-modal-content">

        </div>
    </div>
</div>

<script>
    function buythebook(myself, uid) {
        $.ajax({
            url: '/admin/users/buybook/'+uid,
            data:{},
            type: 'get',
            success: function(result) {
                $('#user-modal-content').html(result);
            }
        });
    }
    function credit(myself, uid) {
        $.ajax({
            url: '/admin/users/credit/'+uid,
            data:{},
            type: 'get',
            success: function(result) {
                $('#user-modal-content').html(result);
            }
        });
    }
</script>