<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-credit-card"></i> Bạn có chắc chắn reset password tài khoản (<?php echo $user->name ?>)</h4>
</div>
<form action="/admin/users/resetpassword/<?php echo $user->getId()?>" method="post" id="creditform">
    <div class="modal-body">
        <div class="row">
            <div class="col-xs-3">
                <img src="<?php if(isset($user->avatar)) echo $user->avatar?>" alt="User Image">
            </div>
           <div class="col-xs-8">
               <?php if ($user->name): ?>
                   <p class=""><b>Username</b> : <?php echo $user->name ?>.</p>
               <?php endif; ?>
               <?php if ($user->email): ?>
                   <p class=""><b>Email</b> : <?php echo $user->email ?>.</p>
               <?php endif; ?>
               <?php if ($user->phone): ?>
                   <p class=""><b>Số điện thoai</b> : <?php echo $user->phone ?>.</p>
               <?php endif; ?>
               <?php if ($user->access_token): ?>
                   <p class=""><b>Token </b>: <?php echo $user->access_token ?>.</p>
               <?php endif; ?>
               <input type="hidden" name="reset" value="<?php echo $user->getId()?>">
            </div>
        </div>
    </div>
    <div class="modal-footer clearfix">
        <button type="button" class="btn btn-xs btn-danger btn-flat" data-dismiss="modal"><i class="fa fa-times"></i> Hủy bỏ</button>
        <button type="submit" class="btn btn-xs btn-primary btn-flat"><i class="fa fa-save"></i> Đồng ý</button>
    </div>
</form>
