<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form('') ?>
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Edit Menu</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12 no-padding">
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Name</label>
                        <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                    </div>
                    <div class="form-group-sm col-md-2 col-sm-12">
                        <label for="status">Active</label>
                        <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                    </div>
                    <div class="form-group-sm col-md-2 col-sm-12">
                        <label for="first_load">First Load</label>
                        <?php echo $this->tag->selectStatic(array("first_load", 'class' => 'form-control'), array("0" => 'NO', "1" => 'YES')) ?>
                    </div>
                    <div class="form-group-sm col-md-2 col-sm-12">
                        <label for="order">Order</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-sort-numeric-desc"></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12" style="margin-top: 20px">
                    <div class="box box-info">
                        <div class="box-header">
                            <h4 class="box-title">Topics</h4>
                        </div>
                        <div class="box-body">
                            <div class="row">
                            <?php foreach($categories as $category): ?>
                                <div class="form-group col-xs-6">
                                    <div class="checkbox">
                                        <label class="">
                                            <input type="checkbox" name="categories[]" value="<?php echo $category->getId() ?>" <?php echo in_array($category->getId(), $categorySelected)?'checked':'' ?> style="position: absolute; opacity: 0;">
                                            <?php echo $category->name ?>
                                        </label>
                                    </div>
                                </div>
                            <?php endforeach;?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->tag->hiddenField("id") ?>
        <div class="box-footer text-right">
            <div class="btn-group-xs">
                <?php echo $this->tag->linkTo(array("menu", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
            </div>
        </div>
    </div>
</div>
</form>
<script type="text/javascript">
    var description = CKEDITOR.replace( 'description' );
    CKFinder.setupCKEditor( description, '../js/ckfinder/' );
    var elmInput = '', elmViewThumb = '';
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }
</script>
