<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-primary btn-flat" type="submit">Search</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-sm">
                <?php echo $this->tag->linkTo(array("menu/new", "<i class='fa fa-plus-circle'></i> | Create Menu", "class"=>"btn btn-small btn-primary")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center small-col">Order</th>
            <th  class="text-left">Name</th>
            <th  class="text-center" width="10%">First Load</th>
            <th  class="text-center" width="5%">Active</th>
            <th  class="text-center" width="15%">Type</th>
            <th  class="text-center" width="15%">Created</th>
            <th  class="text-center" style="width:145px;">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $menu) { ?>
            <tr>
                <td class="small-col text-center"><?php echo $menu->order ?></td>
                <td>
                    <?php echo $this->tag->linkTo(array("menu/edit/" . $menu->_id->{'$id'}, $menu->name)); ?>
                </td>
                <td class="text-center">
                    <?php if($menu->first_load):?>
                        <i class="fa fa-square"></i>
                    <?php else: ?>
                        <i class="fa fa-square-o"></i>
                    <?php endif; ?>
                </td>
                <td class="text-center">
                    <?php
                    if($menu->status) {
                        echo '<label class="label label-success"><i class="fa fa-unlock"></i></label>';
                    } else {
                        echo '<label class="label label-danger"><i class="fa fa-lock"></i></label>';
                    }
                    ?>
                </td>
                <td class="text-center">
                    <?php
                    echo $menu->type ? 'Vertical':'Horizontal';
                    ?>
                </td>
                <td class="text-center"><?php echo Helper::formatDate($menu->created_at) ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("menu/edit/" . $menu->_id->{'$id'}, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("menu/delete/" . $menu->_id->{'$id'}, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<script>
    function activeAccount(myself,id,value) {
        $.ajax({
            type:"POST",
            url:"menu/active",
            data:{id:id,value:value},
            beforeSend: function() {
                $(myself).button('loading');
            },
            success:function(results) {
                $(myself).button('reset');
            },
            error:function() {
                $(myself).button('reset');
                alert("FEHLER!");
            }
        });
    }
</script>