<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form('') ?>
<div class="col-xs-12">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title"><?php echo $t->_('Create menu') ?></h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-xs-12 no-padding">
                    <div class="col-xs-6 no-padding">
                        <div class="form-group-sm col-md-8 col-sm-12">
                            <label for="name"><?php echo $t->_('Menu name') ?></label>
                            <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                        </div>
                        <div class="form-group-sm col-md-4 col-sm-12">
                            <label for="status"><?php echo $t->_('Status') ?></label>
                            <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                        </div>
                        <div class="form-group-sm col-md-4 col-sm-12">
                            <label for="first_load"><?php echo $t->_('First load') ?></label>
                            <?php echo $this->tag->selectStatic(array("first_load", 'class' => 'form-control'), array("0" => 'NO', "1" => 'YES')) ?>
                        </div>
                        <div class="form-group-sm col-md-4 col-sm-12">
                            <label for="order"><?php echo $t->_('Order') ?></label>
                            <div class="input-group input-group-sm col-xs-12">
                                <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                                <span class="input-group-addon"><i class="fa fa-sort-numeric-desc"></i></span>
                            </div>
                        </div>
                        <div class="form-group-sm col-md-4 col-sm-12">
                            <label for="type"><?php echo $t->_('Menu type') ?></label>
                            <?php echo $this->tag->selectStatic(array("type", 'class' => 'form-control'), array("0" => 'Horizontal', "1" => 'Vertical')) ?>
                        </div>
                    </div>
                    <div class="form-group-sm col-sm-2">
                        <label for="image"><?php echo $t->_('Icon') ?></label>
                        <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                            <img src="<?php echo $this->tag->getValue('icon') ?>" class="img-responsive img-rounded img-thumbnail" id="icon_thumb">
                        </div>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("icon", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-flat" type="button" onclick="getImage('icon','icon_thumb');"><i class="fa fa-upload"></i></button>
                                            </span>
                        </div>
                    </div>
                    <div class="form-group-sm col-sm-4">
                        <label for="image"><?php echo $t->_('Image banner') ?></label>
                        <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                            <img src="<?php echo $this->tag->getValue('banner') ?>" class="img-responsive img-rounded img-thumbnail" id="banner_thumb">
                        </div>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("banner", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-flat" type="button" onclick="getImage('banner','banner_thumb');"><i class="fa fa-upload"></i></button>
                                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12" style="margin-top: 20px">
                    <div class="box box-info">
                        <div class="box-header">
                            <h4 class="box-title"><?php echo $t->_('Topics') ?></h4>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <?php foreach($categories as $menu): ?>
                                    <div class="form-group col-xs-6">
                                        <div class="checkbox">
                                            <label class="">
                                                <input type="checkbox" name="categories[]" value="<?php echo $menu->getId() ?>" style="position: absolute; opacity: 0;">
                                                <?php echo $menu->name ?>
                                            </label>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->tag->hiddenField("id") ?>
        <div class="box-footer text-right">
            <div class="btn-group-xs">
                <?php echo $this->tag->linkTo(array("admin/menu/index", "Cancel", "class"=>"btn btn-small btn-primary btn-flat")); ?>
                <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning btn-flat")) ?>
            </div>
        </div>
    </div>
</div>
</form>
<script type="text/javascript">
    var description = CKEDITOR.replace( 'description' );
    CKFinder.setupCKEditor( description, '../js/ckfinder/' );
    var elmInput = '', elmViewThumb = '';
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }
</script>
