<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<div class="col-xs-12 no-padding">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs" role="tablist" id="container_tabs">
            <li role="presentation" class="active">
                <a href="#book" data-controls="book" role="tab" data-toggle="tab">
                    <span class="fa fa-book"></span> Thông tin (<?php echo Helper::limitString($book->name, 25) ?>)
                </a>
            </li>
            <li role="presentation">
                <a href="#chapter" data-controls="chapter" role="tab" data-toggle="tab">
                    <span class="fa fa-bookmark"></span> Danh sách phần/chương
                </a>
            </li>
            <li role="presentation">
                <a href="#search" data-controls="search" role="tab" data-toggle="tab">
                    <span class="fa fa-search"></span> <?php echo $t->_('Search') ?>
                </a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="book">
                <?php echo $this->tag->form("") ?>
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-xs-12">
                        <div class="box box-danger">
                            <div class="box-header">
                                <h3 class="box-title">Thông tin chung</h3>
                            </div>
                            <div class="box-body">
                                <div class="row">
                                    <div class="col-md-6 col-sm-12 no-padding">
                                        <div class="form-group col-sm-12">
                                            <label for="name">Tên sách</label>
                                            <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                                        </div>
                                        <div class="form-group col-sm-12">
                                            <label for="author">Tác giả</label>
                                            <?php echo $this->tag->textField(array("author", "size" => 30, 'class' => 'form-control')) ?>
                                        </div>
                                        <div class="form-group col-sm-12">
                                            <label for="price">Đơn giá</label>
                                            <div class="input-group ">
                                                <span class="input-group-addon">
                                                    Miễn phí:<?php echo $this->tag->checkField(array("free")) ?>
                                                </span>
                                                <?php echo $this->tag->textField(array("price", "size" => 30, 'class' => 'form-control')) ?>
                                                <span class="input-group-addon">VND</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-sm-12 no-padding">
                                        <div class="form-group col-sm-12">
                                            <label for="category_id">Các đề mục</label>
                                            <select name="category_ids[]" multiple class="category_id form-control">
                                                <?php foreach($categories as $cId => $cName): ?>
                                                    <option <?php echo in_array($cId, $book->category_ids)?'selected="selected"':'' ?> value="<?php echo $cId ?>"><?php echo $cName ?></option>
                                                <?php endforeach; ?>
                                            </select>
                                            <?php echo $this->tag->hiddenField('category_odd'); ?>
                                        </div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <label for="description">Mô tả chung</label>
                                        <?php echo $this->tag->textArea(array("description", "rows" => 10,'class' => 'form-control')) ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo $this->tag->hiddenField("id") ?>
                            <div class="box-footer text-right">
                                <div class="btn-group-xs">
                                    <?php echo $this->tag->linkTo(array("admin/books/index", "<i class='fa fa-times'></i> Hủy", "class" => "btn btn-small btn-warning btn-flat")); ?>
                                    <button type="submit" class="btn btn-xs btn-primary btn-flat"><i class="fa fa-save"></i> Lưu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-xs-12">
                        <div class="box box-primary box-solid">
                            <div class="box-body">
                                <div class="row">
                                    <div class="form-group-sm col-xs-12">
                                        <label for="name">Ảnh bìa</label>
                                        <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                                            <img src="<?php echo $book->image ?>" class="img-responsive img-rounded img-thumbnail" id="image_thumb">
                                        </div>

                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("image", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-flat" type="button" onclick="getImage('image','image_thumb');">
                                                    <i class="fa fa-upload"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="active">Xuất bản</label>
                                        <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="rate">Đánh giá</label>

                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->numericField(array("rate", "size" => 30, 'class' => 'form-control', 'readonly' => true)) ?>
                                            <span class="input-group-addon"><i class="fa fa-thumbs-o-up"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="number_buyer">Số người mua</label>

                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->numericField(array("number_buyer", "size" => 30, 'class' => 'form-control', 'readonly' => true)) ?>
                                            <span class="input-group-addon"><i class="fa fa-users"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="name"></label>
                                        <div class="input-group input-group-sm">
                                            <span class="input-group-addon">
                                                Apply for Test:
                                                <?php echo $this->tag->checkField(array("test")) ?>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo $this->tag->endForm() ?>
            </div>
            <div class="tab-pane" id="chapter">
                <?php echo $this->partial('books/_chapters', array('book' => $book)); ?>
            </div>
            <div class="tab-pane" id="search">
                <?php echo $this->partial('books/_search', array('book' => $book)); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var description = CKEDITOR.replace( 'description' );
    CKFinder.setupCKEditor( description, '/js/ckfinder/' );
    var elmInput = '', elmViewThumb = '';
    bookTool.initialize('<?php echo $book->getId() ?>')
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }
    $(function(){
        $(".category_id").select2({
            theme: "classic",
            tags: true,
            tokenSeparators: [',', ' ']
        });
    });
</script>