<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header clearfix">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>" placeholder="<?php echo $t->_('Enter name for search', array('name' => 'Sách'))?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-flat btn-primary" type="submit">Tìm kiếm</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-xs">
                <?php if($this->adminAcl->isAllowed($admin['id'], "books", "new")):?>
                <?php echo $this->tag->linkTo(array("admin/books/new", "<i class='fa fa-plus'></i> | Tạo sách mới", "class"=>"btn btn-xs btn-flat btn-primary")); ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left">Tên sách</th>
            <th class="text-right" style="width: 150px">Đơn giá</th>
            <th class="text-center" width="5%">Ảnh bìa</th>
            <th class="text-center" width="15%">Trạng thái</th>
            <th class="text-center" width="10%">Ngày tạo</th>
            <th class="text-center" style="width:145px;">Công cụ</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $book) { ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td>
                    <?php
                    if((isset($admin['role']) && $role->allowPublish) || in_array($book->getId(),$permissionArr['edit'])) {
                        echo $this->tag->linkTo(array("admin/books/edit/" . $book->getId()->{'$id'}, $book->name));
                    } else {
                        echo $book->name;
                    }
                    ?>
                    <small class="pull-left" style="margin-top:5px;width:100%;font-style:italic;">Tác giả: <?php echo $book->author ?></small>
                </td>
                <td class="text-right"><?php  if($book->price){ echo Helper::formatCurrency($book->price);}else{echo 'Miễn Phí';} ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $book->image ?>"/></td>
                <td class="text-center">
                    <?php $arr=array( "1" => 'NHẬP LIỆU', "0" => 'TESTING','2'=>'XUẤT BẢN','-1'=>'Xoá')?>
                    <?php  if(isset($arr[$book->action])) echo $arr[$book->action]; ?>
                </td>
                <td class="text-center"><?php echo Helper::formatDate($book->created_at) ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php if($book->action!=Helper::ACTION_PRINT){ ?>
                        <?php
                            if((isset($admin['role']) && $role->allowPublish) || in_array($book->getId(),$permissionArr['edit'])) {
                                echo $this->tag->linkTo(array("admin/books/edit/" . $book->getId()->{'$id'}, 'Sửa | <span class="fa fa-edit"></span>', 'class' => 'btn btn-flat btn-warning'));
                            }
                        ?>
                        <?php
                        if(($role && in_array($admin['role']['name'],$this->adminAcl->getPrivateRoles())) || in_array($book->getId(),$permissionArr['delete'])) {
                            echo $this->tag->linkTo(
                                array("admin/books/delete/" . $book->getId()->{'$id'},
                                    'Xóa | <span class="fa fa-trash-o"></span>',
                                    'class' => 'btn btn-flat btn-danger',
                                    'data-toggle' => 'tooltip',
                                    'data-placement' => 'left',
                                    'title' => 'Khi bạn chấp nhận xóa cuốn sách này, hệ thống sẽ đưa nó vào thùng rác.',
                                    'onclick' => 'return confirm("Bạn có chắc chắn muốn xóa cuốn sách này không?");'
                                )
                            );
                        }
                        ?>
                       
                    </div>
                    <?php }else{ ?>
                    <a href="#" class="btn btn-success">Xuất bản | <span class="glyphicon glyphicon-ok"></span></a>
                    <?php }?>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>