<section class="content invoice" id="preview_container">
    <!-- title row -->
    <div class="row">
        <div class="col-xs-12">
            <div class="page-header" style="font-size:16px;font-weight:bold;">
                <i class="fa fa-list"></i> Xem trước danh sách câu hỏi theo từng bài trắc nghiệm.
                <i class="pull-right" style="font-size:12px;font-weight:normal;">Ngày: <?php echo date(Helper::DATE_FORMAT_SHORT) ?></i>
            </div>
        </div><!-- /.col -->
    </div>
    <!-- info row -->
    <div class="row invoice-info">
        <div class="col-xs-12">
            <?php foreach($sectionQuestions as $sectionQuestion): ?>
                <div class="box box-solid">
                    <div class="box-header">
                        <div class="box-title" style="font-size:16px;font-weight:bold;"><?php echo $sectionQuestion->section->name ?></div>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <?php foreach($sectionQuestion->questions as $question): ?>
                                <?php if($question->type == 'GROUP'): ?>
                                    <?php if(isset($groupQuestions[$question->id])): ?>
                                        <?php foreach($groupQuestions[$question->id] as $groupQuestion):?>
                                            <div class="col-xs-12" style="color:#0072b1;margin-top:20px;"><?php echo $groupQuestion->question ?></div>
                                            <div class="col-xs-12">
                                                <?php //echo $question->type ?>
                                                <?php foreach($groupQuestion->answers as $answer): ?>
                                                    <div class="col-xs-12">
                                                        <?php echo Helper::getFullAnswer($groupQuestion->type, $answer) ?>
                                                    </div>
                                                <?php endforeach; ?>
                                            </div>
                                        <?php endforeach; ?>
                                    <?php endif ?>
                                <?php else: ?>
                                    <div class="col-xs-12" style="color:#0072b1;margin-top:20px;"><?php echo $question->question ?></div>
                                    <div class="col-xs-12">
                                        <?php //echo $question->type ?>
                                        <?php foreach($question->answers as $answer): ?>
                                            <div class="col-xs-12">
                                                <?php echo Helper::getFullAnswer($question->type, $answer) ?>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                    <div style="border-top: 1px solid #cccccc;border-bottom: 1px solid #cccccc;background:#f2f2f2;margin: 2%; float: left; width:96%;">
                                        <div class="col-xs-12" style="margin-top: 10px;">
                                            <div style="width: 100%;color:green;"><small>Chú thích khi trả lời đúng:</small></div>
                                            <div style="margin-left:40px;font-style:italic; font-size:12px;"><?php echo $question->correct_msg ?></div>
                                        </div>
                                        <div class="col-xs-12">
                                            <div style="width: 100%;color:orangered;"><small>Chú thích khi trả lời sai:</small></div>
                                            <div style="margin-left:40px;font-style:italic; font-size:12px;"><?php echo $question->incorrect_msg ?></div>
                                        </div>
                                    </div>
                                <?php endif ?>
                            <?php endforeach; ?>
                        </div>
                    </div><!-- /.box-body -->
                </div>
            <?php endforeach; ?>
        </div>
    </div>
    <!-- this row will not appear when printing -->
    <div class="row no-print">
        <div class="col-xs-12">
            <button class="btn btn-xs btn-default pull-right btn-flat" onclick="window.print();"><i class="fa fa-print"></i> Print</button>
        </div>
    </div>
</section><!-- /.content -->

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            processEscapes: true,
            skipStartupTypeset:true
        }
    });
</script>
<script src="/js/MathJax/MathJax.js?config=TeX-AMS_HTML-full" type="text/javascript"></script>
<script>
    var math = document.getElementById('preview_container');
    MathJax.Hub.Queue(["Typeset",MathJax.Hub,math]);
</script>