<div class="text-left col-xs-4 no-padding">
    <form method="get">
        <div class="input-group input-group-sm">
            <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>">
                <span class="input-group-btn">
                    <button id="btn_search" class="btn btn-primary btn-flat" type="submit">Search</button>
                </span>
        </div>
    </form>
</div>
<div class="col-xs-12 no-padding">
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left" width="20%">Name</th>
            <th class="text-right" style="width: 150px">Price</th>
            <th class="text-left">Description</th>
            <th class="text-center" width="5%">Image</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($books as $index => $book) { ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td>
                    <?php echo $book->name?>
                </td>
                <td class="text-right"><?php echo Helper::formatCurrency($book->price) ?></td>
                <td><?php echo Helper::limitString($book->description, 500) ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $book->image ?>"/></td>
            </tr>
        <?php } ?>
    </table>
</div>