<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title"><i class="fa fa-book"></i> Buy the Book (<?php echo $user->name ?>)</h4>
</div>
<form action="#" method="post" id="bookform">
    <div class="modal-body">
        <div class="form-group">
            <div class="input-group">
                <select multiple="multiple" size="10" name="books[]">
                    <?php foreach($books as $book): ?>
                        <option value="<?php echo $book->getId()?>:<?php echo $book->name?>" <?php echo in_array($book->getId(), $bookBought)?'selected disabled': '' ?>><?php echo $book->name ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
    </div>
    <div class="modal-footer clearfix">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>
<script>
    var demo1 = $('select[name="books[]"]').bootstrapDualListbox({
        nonSelectedListLabel: 'Books',
        selectedListLabel: 'Books bought',
        preserveSelectionOnMove: 'moved',
        moveOnSelect: false,
        nonSelectedFilter: '',
        moveAllLabel: ''
    });
    $("#bookform").submit(function() {
        var bookSelected = $('[name="books[]"]').val();
        $.ajax({
            url: 'users/buybook/<?php echo $user->getId() ?>',
            data:{bookSelected:bookSelected},
            type: 'post',
            dataType: 'json',
            success: function(result) {
                console.log(result);
                if(result.error) {
                    alertify.error(result.msg);
                } else {
                    alertify.success(result.msg);
                }
                //window.location.reload();
            },
            error: function(jqXHR){
                alertify.error("Error: Loading data");
            }
        });
        return false;
    });
</script>