<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("users/save") ?>
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Edit users</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-9 no-padding">
                        <div class="form-group-sm col-md-6 col-sm-12">
                            <div class="form-group-sm col-xs-12">
                                <label for="name">Name</label>
                                <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                            </div>
                            <div class="form-group-sm col-xs-12">
                                <label for="name">Email</label>
                                <?php echo $this->tag->textField(array("email", "size" => 30, 'class' => 'form-control')) ?>
                            </div>
                            <div class="form-group-sm col-xs-12">
                                <label for="name">Password</label>
                                <?php echo $this->tag->passwordField(array("password", "size" => 30, 'class' => 'form-control')) ?>
                            </div>
                            <div class="form-group-sm col-xs-12">
                                <label for="name">Phone Number</label>
                                <?php echo $this->tag->textField(array("phone", "size" => 30, 'class' => 'form-control')) ?>
                            </div>
                        </div>
                        <div class="form-group-sm col-md-6 col-sm-12">
                            <label for="name">Avatar</label>
                            <div class="col-xs-4" style="margin-top:10px;padding-left:0;">
                                <img src="<?php echo $user->avatar!=''?$user->avatar:'/img/book_bg.jpg' ?>" class="img-responsive img-rounded img-thumbnail" id="avatar_thumb">
                            </div>
                            <div class="input-group input-group-sm col-xs-8 no-padding">
                                <?php echo $this->tag->textField(array("avatar", "size" => 30, 'class' => 'form-control')) ?>
                                <span class="input-group-btn">
                                    <button class="btn btn-default btn-flat" type="button" onclick="BrowseServer();"><i class="fa fa-upload"></i></button>
                                </span>
                            </div>
                            <div class="form-group-sm col-xs-12 no-padding">
                                <label for="role_id">Role</label>
                                <?php echo $this->tag->select(array("role_id", "rows" => 1, 'class' => 'form-control', $roles)) ?>
                            </div>
                            <div class="form-group-sm col-md-6 col-sm-12 no-padding">
                                <label for="name">Active</label>
                                <?php echo $this->tag->selectStatic(array("active", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h3><?php echo Helper::formatCurrency($user->amount, false)?></h3>
                                <p>Amount Information</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="#" onclick="return viewAmount();" class="small-box-footer">Amound detail</a>
                        </div>
                        <div class="col-xs-12 no-padding">
                                <a class="btn btn-block btn-sm btn-info" data-toggle="modal" data-target="#credit-modal">Credit or debit card</a>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <?php echo $this->tag->linkTo(array("users", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                    <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                </div>
            </div>
        </div>
    </div>
</form>

<!-- Credit modal -->
<div class="modal fade" id="credit-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><i class="fa fa-credit-card"></i> Credit or debit card</h4>
            </div>
            <form action="#" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">TO:</span>
                            <input name="email_to" type="email" class="form-control" placeholder="Email TO">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">CC:</span>
                            <input name="email_to" type="email" class="form-control" placeholder="Email CC">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <span class="input-group-addon">BCC:</span>
                            <input name="email_to" type="email" class="form-control" placeholder="Email BCC">
                        </div>
                    </div>
                    <div class="form-group">
                        <textarea name="message" id="email_message" class="form-control" placeholder="Message" style="height: 120px;"></textarea>
                    </div>
                    <div class="form-group">
                        <div class="btn btn-success btn-file">
                            <i class="fa fa-paperclip"></i> Attachment
                            <input type="file" name="attachment"/>
                        </div>
                        <p class="help-block">Max. 32MB</p>
                    </div>

                </div>
                <div class="modal-footer clearfix">

                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> Discard</button>

                    <button type="submit" class="btn btn-primary pull-left"><i class="fa fa-envelope"></i> Send Message</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }

    // This is a sample function which is called when a file is selected in CKFinder.
    function SetFileField( fileUrl ) {
        document.getElementById('avatar').value = fileUrl;
        document.getElementById('avatar_thumb').src = fileUrl;
    }
</script>
