<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<div class="col-xs-12">
    <div class="pull-right">
        <div class="btn-group-xs">
            <?php echo $this->tag->linkTo(array("users/index", "Go Back", "class"=>"btn btn-small btn-primary")); ?>
            <?php echo $this->tag->linkTo(array("users/new", "Create", "class"=>"btn btn-small btn-primary")); ?>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Avatar</th>
                <th>Device Of Token</th>
                <th>Access Of Token</th>
                <th>Remember Of Token</th>
                <th>Active</th>
                <th>Updated</th>
                <th>Created</th>
                <th style="width: 13%; text-align: center">Action</th>
             </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user) { ?>
            <tr>
                <td><?php echo $user->id ?></td>
                <td><?php echo $user->name ?></td>
                <td><?php echo $user->email ?></td>
                <td><?php echo $user->avatar ?></td>
                <td><?php echo $user->device_token ?></td>
                <td><?php echo $user->access_token ?></td>
                <td><?php echo $user->remember_token ?></td>
                <td><?php echo $user->active ?></td>
                <td><?php echo $user->updated_at ?></td>
                <td><?php echo $user->created_at ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("users/edit/" . $user->id, 'Edit | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("users/delete/" . $user->id, 'Delete | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <ul class="pagination">
            <li class=""><?php echo $this->tag->linkTo("users/search", "First") ?></li>
            <li class="prev"><?php echo $this->tag->linkTo("users/search?page=" . $page->before, "Previous") ?></li>
            <li class="active"><a href="#"><?php echo $page->current, "/", $page->total_pages ?></a></li>
            <li class="next"><?php echo $this->tag->linkTo("users/search?page=" . $page->next, "Next") ?></li>
            <li class=""><?php echo $this->tag->linkTo("users/search?page=" . $page->last, "Last") ?></li>
        </ul>
    </div>
</div>