<ul class="nav nav-pills nav-stacked">
    <li class="header">Phần / Chương</li>
    <?php foreach($chapters as $chapter): ?>
        <li>
            <a onclick="return bookTool.loadSections(this, '<?php echo $chapter->getId() ?>',<?php if(empty($free)) echo 0; else echo $free;?>);" style="cursor: pointer">
                <i class="fa fa-bookmark"></i> <?php echo $chapter->name ?>
            </a>
            <div class="well btn_control btn-info btn-flat">
                <input type="text" id="<?php echo $chapter->getId() ?>" name="sort" value="<?php echo $chapter->order ?>" class="order" style="width: 50px;color: black;">
                <div class="btn btn-xs btn-warning btn-flat" data-toggle="tooltip" title="Sửa phần (chương của sách)" data-loading-text="Editing..." onclick="return bookTool.editChapter(this,'<?php echo $chapter->getId() ?>');"><i class="fa fa-edit"></i></div>
                <div class="btn btn-xs btn-danger btn-flat" data-toggle="tooltip" title="Xóa phần (chương của sách)" data-loading-text="Deleting..." onclick="return bookTool.deleteChapter(this,'<?php echo $chapter->getId() ?>');"><i class="fa fa-trash-o"></i></div>
                <?php echo $this->tag->linkTo(array(
                    "admin/books/preview/" . $chapter->getId().'/chapter',
                    '<i class="fa fa-eye"></i>',
                    'class' => 'btn btn-xs btn-primary btn-flat',
                    'target' => '_blank',
                    'data-toggle' => "tooltip",
                    'title' => "Xem trước danh sách câu hỏi theo từng bài trắc nghiệm",
                    'data-loading-text'=>"Đang tải..."

                )); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>

<script>
    $( ".order" ).focusout(function() {
    var order=$(this).val();
    var id=this.id;
    $.ajax({
            url: '/admin/chapters/order',
            type: "POST",
            data: {order: order, id: id},
            success: function(result) {  
            }
        });
    });
   
    
    $(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $('#chapter_list ul').find('li').hover(
            function() {
                $(this).find('.btn_control').show();//.animate({right: -15},100);
            },
            function() {
                $(this).find('.btn_control').hide();
            }
        )
    })
</script>