<div class="row">
    <div class="col-xs-12">
        <div class="input-group input-group-sm">
            <span class="input-group-addon"><input type="radio" name="answer[]"/></span>
            <input type="text" class="form-control">
            <span class="input-group-addon bg-red fa-border"><i class="fa fa-times"></i></span>
        </div>
    </div>
</div>

<script>
    var template = '';
    template += '<div class="row" style="margin-top:10px;">';
    template +=     '<div class="col-xs-12">';
    template +=         '<div class="input-group input-group-sm">';
    template +=             '<span class="input-group-addon"><input type="radio" name="answer[]"/></span>';
    template +=             '<input type="text" class="form-control">';
    template +=             '<span class="input-group-addon bg-red fa-border"><i class="fa fa-times"></i></span>';
    template +=         '</div>';
    template +=     '</div>';
    template += '</div>';
    function addmore() {
        $('#question_answer').append(template);
    }
</script>