<div class="box box-danger">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-stack-overflow"></i> <?php echo $this->tag->getValue('id')==''?'Create':'Edit'?> Section</h3>
    </div>
    <div class="box-body">
        <form action="#" method="post" id="section_form">
            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group-sm col-xs-6 no-padding">
                        <div class="input-group input-group-sm col-xs-12">
                            <label for="name">Name</label>
                            <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control', 'placeholder' => 'Enter Name')) ?>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-3">
                        <label for="time">Time</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("time", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-clock-o"></i>
                            </span>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-3 no-padding">
                        <label for="check_question">Check question</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->selectStatic(array("check_question", "rows" => 1, 'class' => 'form-control'), Helper::getOptionsCheckQuestion()) ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group-sm col-xs-6 no-padding">
                        <label for="type">Type</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->selectStatic(array("type", "rows" => 1, 'class' => 'form-control'), \Books\App\Models\Sections::getTypes()) ?>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-2">
                        <label for="status">Active</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->selectStatic(array("status", "rows" => 1, 'class' => 'form-control'), Helper::getOptionsStatus()) ?>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-4 no-padding">
                        <label for="order">Order</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-sort-numeric-desc"></i>
                            </span>
                            <span class="input-group-addon">
                                <div class="input-group input-group-sm col-xs-12">
                                    Free: <?php echo $this->tag->checkField(array("free", 'value' => 1)) ?>
                                </div>
                            </span>
                        </div>
                    </div>

                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <label for="content">Content</label>
                        <?php echo $this->tag->textArea(array("content", "rows" => 6, 'id' => 'section_content','class' => 'form-control','placeholder'=>'Enter content')) ?>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField(array("id")) ?>
            <?php echo $this->tag->hiddenField(array("chapter_id")) ?>
            <div class="modal-footer clearfix" style="padding: 10px 0;">
                <button type="button" class="btn btn-xs btn-warning" onclick="return bookTool.resetForm(this,'section')"><i class="fa fa-times"></i> Cancel</button>
                <button type="button" class="btn btn-xs btn-primary" onclick="return bookTool.saveSection(this)"><i class="fa fa-save"></i> Save</button>
            </div>
        </form>
    </div><!-- /.box-body -->
</div>
<script type="text/javascript">
    var section_content = CKEDITOR.replace('section_content');
    CKFinder.setupCKEditor( section_content, '/js/ckfinder/' );
    section_content.on( 'change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#section_content').html(evt.editor.getData());
    });
</script>