<div class="mailbox row">
    <div class="col-md-3 col-sm-4" id="chapter_left" style="height: 100%">
        <a class="btn btn-block btn-primary" onclick="return bookTool.editChapter(this);">Tạo phần (chương của sách)</a>
        <div style="margin-top: 15px;" id="chapter_list">

        </div>
    </div>
    <div class="col-md-9 col-sm-8" id="chapter_right">
        <div id="chapter_container">
            Chọn Phần/ Chương để xem nội dung tiếp ...
        </div>
    </div>
</div>
<script>
    $(function(){
        $('[data-toggle="tooltip"]').tooltip();
    })
</script>