<div class="mailbox row">
    <div class="col-md-3 col-sm-4">
        <a class="btn btn-block btn-primary" data-toggle="modal" data-target="#compose-modal">Create Chapter</a>
        <div style="margin-top: 15px;">
            <ul class="nav nav-pills nav-stacked">
                <li class="header">Chapters</li>
                <?php for($i=1; $i<11; $i++): ?>
                <li><a href="#" onclick="return bookTool.loadQuestions(this, '<?php echo $i ?>');" ><i class="fa fa-bookmark"></i> Chuong sach <?php echo $i ?></a></li>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
    <div class="col-md-9 col-sm-8">
        <div id="chapter_container">
            Please click to chapter to loading data ...
        </div>
    </div>
</div>