<div class="row pad">
    <div class="box-header">
        <h4 class="box-title"><span class="fa fa-stack-overflow"></span> All Sections in (<?php echo $book->name ?>) </h4>
    </div>
</div>
<div class="table-responsive" id="find_sections_container">
    <!-- THE MESSAGES -->
    <table class="table table-mailbox table-bordered table-hover ">
        <tr class="unread">
            <td class="small-col"><input type="checkbox" name="checkAll"/></td>
            <td class="title">Name</td>
            <td class="text-center" style="width: 10%">Status</td>
            <td class="text-right" style="width: 20%">Type</td>
            <td style="width: 15%" class="text-center">Action</td>
        </tr>

    </table>
</div><!-- /.table-responsive -->