<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>" placeholder="<?php echo $t->_('Enter name for search', array('name' => 'Sách'))?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-flat btn-primary" type="submit">Tìm kiếm</button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-sm">
                <?php echo $this->tag->linkTo(array("books/new", "<i class='fa fa-plus-circle'></i> | Tạo sách mới", "class"=>"btn btn-xs btn-flat btn-primary")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th class="text-center small-col">#</th>
            <th class="text-left">Tên sách</th>
            <th class="text-right" style="width: 150px">Đơn giá</th>
            <th class="text-left">Mô tả</th>
            <th class="text-center" width="5%">Ảnh bìa</th>
            <th class="text-center" width="5%">Trạng thái</th>
            <th class="text-center" width="10%">Ngày tạo</th>
            <th class="text-center" style="width:145px;">Công cụ</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $book) { ?>
            <?php
            if($book->status) {
                $linkLock = '<label class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr>
                <td><?php echo $index+1 ?></td>
                <td>
                    <?php echo $this->tag->linkTo(array("books/edit/" . $book->getId()->{'$id'}, '<span class="fa fa-info-circle"></span> '. $book->name)); ?>
                </td>
                <td class="text-right"><?php echo Helper::formatCurrency($book->price) ?></td>
                <td><?php echo Helper::limitString($book->description, 100) ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $book->image ?>"/></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-center"><?php echo Helper::formatDate($book->created_at) ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("books/edit/" . $book->getId()->{'$id'}, 'Sửa | <span class="fa fa-edit"></span>', 'class' => 'btn btn-flat btn-warning')); ?>
                        <?php echo $this->tag->linkTo(array("books/delete/" . $book->getId()->{'$id'}, 'Xóa | <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-flat btn-danger', 'onclick' => 'return confirm("Do you want to delete this book?");')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>