<?php echo $this->getContent(); ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="btn-group-xs dropdown">
            <button class="btn btn-small btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <i class='fa fa-plus-circle'></i> | Create Question
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><a href="books/create">Single choice Answer</a></li>
                <li><a href="books/create">Multi choice Answer</a></li>
                <li><a href="books/create">List Answer</a></li>
                <li><a href="books/create">Push text Answer</a></li>
            </ul>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center">Name</th>
            <th  class="text-center">Avatar</th>
            <th  class="text-center">Price</th>
            <th  class="text-center">Category</th>
            <th  class="text-center">Author</th>
            <th  class="text-center">Published</th>
            <th  class="text-center">Created at</th>
            <th  class="text-center" style="width: 13%;">Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Book1</td>
            <td class="text-center">
                <img src="/img/book_bg.jpg" width="50" class="img-responsive img-thumbnail"/>
            </td>
            <td class="text-right">100000 VND</td>
            <td>Chuyen muc 1</td>
            <td>No name</td>
            <td class="text-center">
                <label onclick="return activeAccount(this);" class="label label-success"><i class="fa fa-unlock"></i></label>
            </td>
            <td>10/10/2015</td>
            <td><a href="books/create">Questions</a></td>

        </tr>
        </tbody>
    </table>
</div>