<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("books/new?showchap=1") ?>
<div class="col-xs-12 no-padding">
    <div class="nav-tabs-custom">
        <ul class="nav nav-tabs" role="tablist" id="container_tabs">
            <li role="presentation" class="active"><a href="#book" data-controls="book" role="tab" data-toggle="tab"><span class="fa fa-book"></span> Book Information</a></li>
            <li role="presentation" class="disabled"><a href="#chapter" data-controls="chapter" role="tab"><span class="fa fa-bookmark"></span> Chapters</a></li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active" id="book">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-xs-12">
                        <div class="box box-primary box-solid">
                            <div class="box-header">
                                <h3 class="box-title">Create Book</h3>
                            </div>
                            <div class="box-body">
                                <div class="row">
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="title">Title</label>
                                        <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="category">Category</label>
                                        <?php echo $this->tag->selectStatic(array("category_id", 'class' => 'form-control'), $categories) ?>
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="author">Author Name</label>
                                        <?php echo $this->tag->textField(array("author", "size" => 30, 'class' => 'form-control')) ?>
                                    </div>
                                    <div class="form-group col-md-6 col-sm-12">
                                        <label for="price">Price</label>
                                        <div class="input-group ">
                                            <span class="input-group-addon">Free: <input type="checkbox" class="minimal-red" name="free"></span>
                                            <input type="text" class="form-control" name="price">
                                            <span class="input-group-addon">VND</span>
                                        </div>
                                    </div>
                                    <div class="form-group col-md-12 col-sm-12">
                                        <label for="name">Description</label>
                                        <?php echo $this->tag->textArea(array("description", "rows"=>10, 'class' => 'form-control')) ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo $this->tag->hiddenField("id") ?>
                            <div class="box-footer text-right">
                                <div class="btn-group-xs">
                                    <?php echo $this->tag->linkTo(array("books", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                                    <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-xs-12">
                        <div class="box box-primary box-solid">
                            <div class="box-header">
                                <h3 class="box-title">Information</h3>
                            </div>
                            <div class="box-body">
                                <div class="row">
                                    <div class="form-group-sm col-xs-12">
                                        <label for="name">Avatar</label>
                                        <img src="/img/book_bg.jpg" class="img-responsive img-circle" id="image_thumb">
                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("image", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-btn">
                                                <button class="btn btn-default btn-flat" type="button" onclick="BrowseServer();"><i class="fa fa-upload"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="created_by">Created By</label>
                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("created_by", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="modified_by">Modified By</label>
                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("modified_by", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-addon"><i class="fa fa-user"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="active">Publish</label>
                                        <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="rate">Rate</label>
                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("rate", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-addon"><i class="fa fa-thumbs-o-up"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="viewer">Viewer</label>
                                        <div class="input-group input-group-sm">
                                            <?php echo $this->tag->textField(array("viewer", "size" => 30, 'class' => 'form-control')) ?>
                                            <span class="input-group-addon"><i class="fa fa-users"></i></span>
                                        </div>
                                    </div>
                                    <div class="form-group-sm col-xs-12">
                                        <label for="name"></label>
                                        <div class="input-group input-group-sm">
                                        <span class="input-group-addon">
                                            Apply for Test:
                                            <input type="checkbox" name="test">
                                        </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="chapter"></div>
        </div>
    </div>
</div>

</form>