<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("books/new?showchap=1") ?>
    <div class="col-xs-12 no-padding">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs" role="tablist" id="container_tabs">
                <li role="presentation" class="active"><a href="#book" data-controls="book" role="tab" data-toggle="tab"><span class="fa fa-book"></span> Book Information</a></li>
                <li role="presentation" class="disabled"><a href="#chapter" data-controls="chapter" role="tab"><span class="fa fa-bookmark"></span> Chapters</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="book">
                    <div class="row">
                        <div class="col-lg-8 col-md-8 col-xs-12">
                            <div class="box box-primary box-solid">
                                <div class="box-header">
                                    <h3 class="box-title">Create Book</h3>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-12 no-padding">
                                            <div class="form-group col-sm-12">
                                                <label for="name">Name</label>
                                                <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                                            </div>
                                            <div class="form-group col-sm-12">
                                                <label for="author">Author Name</label>
                                                <?php echo $this->tag->textField(array("author", "size" => 30, 'class' => 'form-control')) ?>
                                            </div>
                                            <div class="form-group col-sm-12">
                                                <label for="price">Price</label>
                                                <div class="input-group ">
                                                <span class="input-group-addon">
                                                    Free:<?php echo $this->tag->checkField(array("free")) ?>
                                                </span>
                                                    <?php echo $this->tag->textField(array("price", "size" => 30, 'class' => 'form-control')) ?>
                                                    <span class="input-group-addon">VND</span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-sm-12 no-padding">
                                            <div class="form-group col-xs-12">
                                                <label for="category">Topic</label>
                                                <?php echo $this->tag->selectStatic(array("category_id[]", 'multiple'=>'multiple', 'class' => 'category_id form-control'), $categories) ?>
                                            </div>
                                        </div>
                                        <div class="form-group col-md-12 col-sm-12">
                                            <label for="name">Description</label>
                                            <?php echo $this->tag->textArea(array("description", "rows"=>10, 'class' => 'form-control')) ?>
                                        </div>
                                    </div>
                                </div>
                                <?php echo $this->tag->hiddenField("id") ?>
                                <div class="box-footer text-right">
                                    <div class="btn-group-xs">
                                        <?php echo $this->tag->linkTo(array("books", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                                        <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-xs-12">
                            <div class="box box-primary box-solid">
                                <div class="box-header">
                                    <h3 class="box-title">Information</h3>
                                </div>
                                <div class="box-body">
                                    <div class="row">
                                        <div class="form-group-sm col-xs-12">
                                            <label for="name">Avatar</label>
                                            <div class="col-xs-12 no-padding" style="margin-bottom:10px;padding-left:0;">
                                                <img src="<?php echo $book->image ?>" class="img-responsive img-rounded img-thumbnail" id="image_thumb">
                                            </div>
                                            <div class="input-group input-group-sm">
                                                <?php echo $this->tag->textField(array("image", "size" => 30, 'class' => 'form-control')) ?>
                                                <span class="input-group-btn">
                                                    <button class="btn btn-default btn-flat" type="button" onclick="getImage('image','image_thumb');"><i class="fa fa-upload"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="form-group-sm col-xs-12">
                                            <label for="active">Publish</label>
                                            <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                                        </div>
                                        <div class="form-group-sm col-xs-12">
                                            <label for="rate">Rate</label>
                                            <div class="input-group input-group-sm">
                                                <?php echo $this->tag->textField(array("rate", "size" => 30, 'class' => 'form-control')) ?>
                                                <span class="input-group-addon"><i class="fa fa-thumbs-o-up"></i></span>
                                            </div>
                                        </div>
                                        <div class="form-group-sm col-xs-12">
                                            <label for="viewer">Viewer</label>
                                            <div class="input-group input-group-sm">
                                                <?php echo $this->tag->textField(array("viewer", "size" => 30, 'class' => 'form-control')) ?>
                                                <span class="input-group-addon"><i class="fa fa-users"></i></span>
                                            </div>
                                        </div>
                                        <div class="form-group-sm col-xs-12">
                                            <label for="name"></label>
                                            <div class="input-group input-group-sm">
                                            <span class="input-group-addon">
                                                Apply for Test:
                                                <input type="checkbox" name="test">
                                            </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane" id="chapter"></div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    var description = CKEDITOR.replace( 'description' );
    CKFinder.setupCKEditor( description, '/js/ckfinder/' );
    var elmInput = '', elmViewThumb = '';
    function getImage(elementInput, elementViewthumb) {
        elmInput = elementInput;
        elmViewThumb = elementViewthumb;
        var finder = new CKFinder();
        finder.selectActionFunction = setImageField;
        finder.popup();
    }
    // This is a sample function which is called when a file is selected in CKFinder.
    function setImageField( fileUrl ) {
        document.getElementById(elmInput).value = fileUrl;
        document.getElementById(elmViewThumb).src = fileUrl;
    }
    $(function(){
        $(".category_id").select2({
            theme: "classic",
            tags: true,
            tokenSeparators: [',', ' ']
        });
    });
</script>