<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<?php echo $this->tag->form("books/save") ?>
    <div class="col-lg-7 col-md-7 col-xs-12">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Create Book</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Name</label>
                        <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control')) ?>
                    </div>
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Avatar</label>
                        <?php echo $this->tag->fileField(array("avatar", "size" => 30, 'class' => 'form-control')) ?>
                    </div>
                    <div class="form-group col-md-12 col-sm-12">
                        <label for="name">Description</label>
                        <?php echo $this->tag->textArea(array("description", 'This is the content of the text-area', "rows"=>10, 'class' => 'form-control')) ?>
                    </div>
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Active</label>
                        <?php echo $this->tag->selectStatic(array("active", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                    </div>
                    <div class="form-group-sm col-md-6 col-sm-12">
                        <label for="name">Type</label>
                        <?php echo $this->tag->selectStatic(array("type", 'class' => 'form-control'), array("single" => 'Single choice', "multichoice" => 'Multi choice')) ?>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <?php echo $this->tag->linkTo(array("users", "Cancel", "class"=>"btn btn-small btn-primary")); ?>
                    <?php echo $this->tag->submitButton(array("Save","class"=>"btn btn-small btn-warning")) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-5 col-md-5 col-xs-12">
        <div class="box box-success">
            <div class="box-header">
                <h3 class="box-title">Questions & Answers</h3>
            </div>
            <div class="box-body">
                <div id="question_answer"></div>
            </div>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <a href="#" onclick="addmore();" class="btn btn-small btn-warning">Add more</a>
                </div>
            </div>
        </div>
    </div>
</form>