<div class="header_title"><?php echo $t->_('Question type') . ': ' . $t->_('Free Text') ?></div>
<ul class="answerList list-unstyled">
    <li style="border-bottom:1px dotted #ccc; padding-bottom: 5px; margin-bottom: 10px;" class="bg-light-gray">
        <?php echo $this->tag->textArea(array("answers[answer]", "id" => "answers_text", "value" => isset($answers['answer']) ? $answers['answer'] : '', "rows" => 10, 'class' => 'form-control')) ?>
    </li>
</ul>
<script>
    /*var editor = CKEDITOR.inline("answers[text]");
     editor.on('change', function(evt) {
     // getData() returns CKEditor's HTML content.
     $('#answers_text').html(evt.editor.getData());
     });*/
</script>