<div class="header_title">
    <?php echo $t->_('Question type') . ': ' . $t->_('Question group') ?>
    <div class="dropdown pull-right">
        <div class="btn-group">
            <button class="btn btn-xs btn-warning btn-flat dropdown-toggle" type="button" id="create_group" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-plus"></i> | <?php echo $t->_('Add more group') ?>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu" aria-labelledby="create_group">
                <li><a onclick="return bookTool.editGroupQuestion(this, '','SINGLE');"><?php echo $t->_('Single Choice') ?></a></li>
                <li><a onclick="return bookTool.editGroupQuestion(this, '','MULTI');"><?php echo $t->_('Multi Choice') ?></a></li>
                <li><a onclick="return bookTool.editGroupQuestion(this, '','FREE_TEXT');"><?php echo $t->_('Free Text') ?></a></li>
                <li><a onclick="return bookTool.editGroupQuestion(this, '','PLACE_ANSWER_IMAGE');"><?php echo $t->_('Place Answer Image') ?></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="question_answer_group">
    <div class="question_childs">
        <?php
        if(isset($groupQuestions)) {
            foreach ($groupQuestions as $index => $groupQuestion) {
                $this->partial('questions/types/groups/' . strtolower($groupQuestion->question_group_type), array('groupQuestion' => $groupQuestion, 'groupIndex' => $index));
            }
        }
        ?>
    </div>
</div>
<style>
    .question_group {
        padding: 10px;
        /*-webkit-box-shadow: 0px 10px 15px -1px rgba(0,0,0,0.75);
        -moz-box-shadow: 0px 10px 15px -1px rgba(0,0,0,0.75);
        box-shadow: 0px 10px 15px -1px rgba(0,0,0,0.75);*/
        -webkit-box-shadow: 0px 0px 15px 3px rgba(0,0,0,0.5);
        -moz-box-shadow: 0px 0px 15px 3px rgba(0,0,0,0.5);
        box-shadow: 0px 0px 15px 3px rgba(0,0,0,0.5);
        border: 1px solid #cccccc;
        margin-bottom: 30px;
    }
    .header_title {
        font-weight: bold;
    }

</style>