<div class="header_title">Multi Choice (Translate)</div>
<?php for($i=0;$i<4;$i++): ?>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-xs-12">
            <div class="input-group">
                <input type="text" class="form-control" value="<?php echo isset($answers['text'][$i])?$answers['text'][$i]:'' ?>" name="translates[answers][text][<?php echo $i ?>]">
                <span class="input-group-btn">
                    <button type="button" class="btn btn-danger" onclick="removeTransItem(this);"><i class="fa fa-times"></i> </button>
                </span>
            </div>
        </div>
    </div>
<?php endfor; ?>
<script>
    var index_trans = 4;
    function addTransMore() {
        var template = '';
        template += '<div class="row" style="margin-bottom: 10px;">';
        template +=     '<div class="col-xs-12">';
        template +=         '<div class="input-group input-group">';
        template +=             '<input type="text" class="form-control" name="translates[answers][text]['+index_trans+']">';
        template +=             '<span class="input-group-btn">';
        template +=                 '<button type="button" class="btn btn-danger" onclick="removeTransItem(this);"><i class="fa fa-times"></i> </button>';
        template +=             '</span>';
        template +=         '</div>';
        template +=     '</div>';
        template += '</div>';
        $('#translate_question_answer').append(template);
        index_trans++;
    }
    function removeTransItem(myself) {
        $(myself).parent().parent().remove();
    }
</script>