<div class="header_title">Multi Choice</div>
<?php for($i=0;$i<4;$i++): ?>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-xs-12">
            <div class="input-group">
                <span class="input-group-addon">
                    <input type="checkbox" value="<?php echo $i ?>" <?php echo (isset($answers[$i]['correct']) && $answers[$i]['correct'] == 'on')?'checked':'' ?> name="answers[correct][<?php echo $i ?>]"/>
                </span>
                <input type="text" class="form-control" value="<?php echo isset($answers[$i]['text'])?$answers[$i]['text']:'' ?>" name="answers[text][<?php echo $i ?>]">
                <span class="input-group-btn">
                    <button type="button" class="btn btn-danger" onclick="removeItem(this);"><i class="fa fa-times"></i> </button>
                </span>
            </div>
        </div>
    </div>
<?php endfor; ?>
<script>
    var index = 4;
    function addmore() {
        var template = '';
        template += '<div class="row" style="margin-bottom: 10px;">';
        template +=     '<div class="col-xs-12">';
        template +=         '<div class="input-group input-group">';
        template +=             '<span class="input-group-addon"><input type="radio" value="'+index+'" name="answers[correct]"/></span>';
        template +=             '<input type="text" class="form-control" name="answers[text]['+index+']">';
        template +=             '<span class="input-group-btn">';
        template +=                 '<button type="button" class="btn btn-danger" onclick="removeItem(this);"><i class="fa fa-times"></i> </button>';
        template +=             '</span>';
        template +=         '</div>';
        template +=     '</div>';
        template += '</div>';
        $('#question_answer').append(template);
        $("input[type='checkbox']:not(.simple), input[type='radio']:not(.simple)").iCheck({
            checkboxClass: 'icheckbox_minimal',
            radioClass: 'iradio_minimal'
        });
        index++;
    }
    function removeItem(myself) {
        $(myself).parent().parent().remove();
    }
</script>