<div class="header_title"><?php echo $t->_('Question type') . ': ' . $t->_('Place Answer Text') ?></div>
<div style="font-size: 13px; font-style: italic;margin:2px 0 5px;">Các câu trả lời đúng (Lần lượt từ trên xuống dưới theo thứ tự)</div>
<ul class="answerList list-unstyled">
    <?php if(count($answers)):?>
        <?php foreach($answers as $index => $answer): ?>
            <li style="border-bottom:1px dotted #ccc; padding-bottom: 5px; margin-bottom: 10px;" class="bg-light-gray">
                <table class="table table-bordered" style="margin-bottom:10px;">
                    <tr>
                        <th><?php echo $t->_('Answer')?></th>
                    </tr>
                    <tr>
                        <td style="padding: 5px; vertical-align: top;">
                            <div style="display: none;">
                                <input type="number" class="small-text answer_sl" name="answers[sl][]" value="1">
                            </div>
                            <textarea rows="1" class="form-control answer_text" name="answers[answer][]" style="resize:vertical;"><?php echo $answer['answer']?></textarea>
                        </td>
                    </tr>
                </table>
                <div class="btn-group-xs">
                    <button type="button" class="btn btn-danger btn-flat" onclick="return bookAnswer.answerRemove(this);"><i class="fa fa-times"></i> | <?php echo $t->_('Delete answer')?></button>
                </div>
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li style="border-bottom:1px dotted #ccc; padding-bottom: 5px; margin-bottom: 10px;" class="bg-light-gray">
            <table class="table table-bordered" style="margin-bottom:10px;">
                <tr>
                    <th><?php echo $t->_('Answer')?></th>
                </tr>
                <tr>
                    <td style="padding: 5px; vertical-align: top;">
                        <div style="display: none;">
                            <input type="number" class="small-text answer_sl" name="answers[sl][]" value="1">
                        </div>
                        <textarea rows="1" class="form-control answer_text" name="answers[answer][]" style="resize:vertical;"></textarea>
                    </td>
                </tr>
            </table>
            <div class="btn-group-xs">
                <button type="button" class="btn btn-danger btn-flat" onclick="return bookAnswer.answerRemove(this);"><i class="fa fa-times"></i> | <?php echo $t->_('Delete answer')?></button>
            </div>
        </li>
    <?php endif; ?>
</ul>
<button type="button" class="btn btn-primary btn-flat btn-xs" onclick="return bookAnswer.addAnswer(this);"><i class="fa fa-plus"></i> | <?php echo $t->_('Add more answer')?></button>