<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link rel="shortcut icon" href="/img/favicon.png">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/font-awesome.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/ionicons.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/admin.css" type="text/css" />
    <link rel="stylesheet" href="/css/datatables/dataTables.bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="/css/daterangepicker/daterangepicker-bs3.css" type="text/css" />
    <link rel="stylesheet" href="/js/plugins/jquery.alert/alertify.core.css" type="text/css" />
    <link rel="stylesheet" href="/js/plugins/bootstrapvalidator/css/bootstrapValidator.min.css" type="text/css" />
    <?php echo $this->assets->outputCss(); ?>
    <title>Olay</title>
    <script src="/js/jquery-2.1.4.min.js" type="text/javascript"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/plugins/jquery.alert/alertify.min.js" type="text/javascript"></script>
    <script src="/js/ckeditor/ckeditor.js"></script>
    <script src="/js/ckeditor/adapters/jquery.js"></script>
    <script src="/js/ckfinder/ckfinder.js" type="text/javascript"></script>
    <script src="/js/plugins/bootstrapvalidator/js/bootstrapValidator.js" type="text/javascript"></script>
    <?php echo $this->assets->outputJs(); ?>
</head>
<body class="skin-blue">
<header class="header">
    <a href="index.html" class="logo">Olay</a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i>
                        <span><?php echo $admin['name'] ?> <i class="caret"></i></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header bg-light-blue">
                            <img src="<?php echo $admin['avatar'] ?>" class="img-circle" alt="User Image" />
                            <p>
                                <?php echo $admin['name'] ?>
                                <small><?php echo date('l jS \of F Y h:i:s A',time()) ?></small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-right">
                                <a href="/admin/auth/logout" class="btn btn-default btn-flat">Logout</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper row-offcanvas row-offcanvas-left">
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="left-side sidebar-offcanvas">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="<?php echo $admin['avatar'] ?>" class="img-circle" alt="User Image" />
                </div>
                <div class="pull-left info">
                    <p>Hi, <?php echo $admin['name'] ?></p>
                    <a href="#"><i class="fa fa-circle text-success"></i> <?php echo $admin['email'] ?></a>
                </div>
            </div>
            <?php $this->partial('layouts/sidebar'); ?>
        </section>
    </aside>

    <aside class="right-side">
        <section class="content-header">
            <h1>
                <?php echo $title ?>
                <small></small>
            </h1>
            <?php if (isset($bc)) { ?>
                <ol class="breadcrumb">
                    <?php foreach ($bc as $breadcrumb) { ?>
                        <li class="active"><i class="fa"></i> <a href="<?php echo $breadcrumb['link']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
                    <?php } ?>
                </ol>
            <?php } ?>
        </section>

        <!-- Main content -->
        <section class="content">
            <?php echo $this->getContent() ?>
        </section>
    </aside>
</div>
</body>
<footer>
    <script src="/js/app.js" type="text/javascript"></script>
</footer>
</html>
