<div class="box box-danger">
    <div class="box-header">
        <h3 class="box-title"><i class="fa fa-bookmark"></i> <?php echo $this->tag->getValue('id')==''?'Tạo':'Sửa'?> phần (chương của sách)</h3>
    </div>
    <div class="box-body">
        <form action="#" method="post" id="chapter_form">
            <div class="modal-body">
                <div class="row">
                    <div class="form-group-sm col-xs-6 no-padding">
                        <div class="input-group input-group-sm col-xs-12">
                            <label for="name">Tên phần</label>
                            <?php echo $this->tag->textField(array("name", "size" => 30, 'class' => 'form-control','placeholder'=>'Nhập tên phần')) ?>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-4">
                        <label for="number_display">Số mục hiển thị trong mỗi phần</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("number_display", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-sort-numeric-asc"></i>
                            </span>
                        </div>
                    </div>
                    <div class="form-group-sm col-xs-2 no-padding">
                        <label for="order">Thứ tự</label>
                        <div class="input-group input-group-sm col-xs-12">
                            <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                            <span class="input-group-addon">
                                <i class="fa fa-sort-numeric-desc"></i>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Mô tả</label>
                        <?php echo $this->tag->textArea(array("description", "rows" => 6, 'id' => 'chapter_description','class' => 'form-control','placeholder'=>'Enter Description')) ?>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField(array("id")) ?>
            <?php echo $this->tag->hiddenField(array("book_id")) ?>
            <div class="modal-footer clearfix" style="padding: 10px 0;">
                <button type="button" class="btn btn-xs btn-warning btn-flat" onclick="return bookTool.resetForm(this,'chapter')"><i class="fa fa-times"></i> Hủy</button>
                <button type="button" class="btn btn-xs btn-primary btn-flat" onclick="return bookTool.saveChapter(this)"><i class="fa fa-save"></i> Lưu</button>
            </div>
        </form>
    </div><!-- /.box-body -->
</div>
<script type="text/javascript">
    var chapter_description = CKEDITOR.replace( 'chapter_description' );
    chapter_description.on( 'change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#chapter_description').html(evt.editor.getData());
    });
</script>