<div class="row pad">
    <div class="box-header">
        <div class="box-title"><span class="fa fa-stack-overflow"></span> <strong><?php echo $chapter->name ?></strong> > Sections
            <div class="pull-right" style="margin-right: 5px">
                <button class="btn btn-xs btn-primary" onclick="return bookTool.editSection(this, 0);"><i class="fa fa-plus"></i> | Create Section</button>
            </div>
        </div>
    </div>
</div>
<div class="table-responsive" id="sections_container">
    <!-- THE MESSAGES -->
    <table class="table table-mailbox table-bordered table-hover ">
        <tr class="unread">
            <td class="small-col"><input type="checkbox" name="checkAll"/></td>
            <td class="title">Name</td>
            <td class="text-center" style="width: 10%">Status</td>
            <td class="text-right" style="width: 20%">Type</td>
            <td style="width: 15%" class="text-center">Action</td>
        </tr>
        <?php foreach($chapter->sections as $section):?>
            <?php
            if($section['status']) {
                $linkLock = '<label class="label label-success"><i class="fa fa-unlock"></i></label>';
            } else {
                $linkLock = '<label class="label label-danger"><i class="fa fa-lock"></i></label>';
            }
            ?>
            <tr class="">
                <td class="small-col"><input type="checkbox" /></td>
                <td class="title"><?php echo $section['name'] ?></td>
                <td class="text-center"><?php echo $linkLock ?></td>
                <td class="text-right"><?php echo $section['type'] ?></td>
                <td class="text-center">
                    <button class="btn btn-xs btn-info" onclick="return bookTool.loadQuestions(this, '<?php echo $section['id'] ?>');"><i class="fa fa-question"></i> | Questions</button>
                    <button class="btn btn-xs btn-warning" onclick="return bookTool.editSection(this, '<?php echo $section['id'] ?>');"><i class="fa fa-pencil"></i> | Edit</button>
                    <button class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> | Del</button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div><!-- /.table-responsive -->