<div class="header_title"><?php echo $t->_('Question type') . ': ' . $t->_('Free Text') ?></div>
<small class="description">Với loại câu hỏi này chúng ta sử dụng cho trường hợp 1 hay nhiều đáp án. nhu x=5 y=6 ... </small>
<ul class="answerList list-unstyled">
    <?php if(count($answers)):?>
        <?php foreach($answers as $index => $answer): ?>
            <li style="border-bottom:1px dotted #ccc; padding-bottom: 5px; margin-bottom: 10px;" class="bg-light-gray">
                <table class="table table-bordered" style="margin-bottom:10px;">
                    <tr>
                        <th style="width:90px"><?php echo $t->_('Variable name')?></th>
                        <th><?php echo $t->_('Answer')?></th>
                    </tr>
                    <tr>
                        <td>
                            <div style="display: none;">
                                <input type="number" class="small-text answer_sl" name="answers[sl][]" value="1">
                            </div>
                            <input type="text" class="answer_variable" name="answers[variable][]" value="<?php echo $answer['variable']?>" placeholder="Tên biến">
                        </td>
                        <td style="padding: 5px; vertical-align: top;">
                            <input type="text" class="form-control answer_text" name="answers[answer][]" value="<?php echo $answer['answer']?>" placeholder="<?php echo $t->_('Correct answer')?>">
                        </td>
                    </tr>
                </table>
                <div class="btn-group-xs">
                    <button type="button" class="btn btn-danger btn-flat" onclick="return bookAnswer.answerRemove(this);"><i class="fa fa-times"></i> | <?php echo $t->_('Delete answer')?></button>
                    <button type="button" class="btn btn-default btn-flat" style="cursor: move;"><i class="fa fa-arrows-alt"></i> | <?php echo $t->_('Move')?></button>
                </div>
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li style="border-bottom:1px dotted #ccc; padding-bottom: 5px; margin-bottom: 10px;" class="bg-light-gray">
            <table class="table table-bordered" style="margin-bottom:10px;">
                <tr>
                    <th style="width:90px"><?php echo $t->_('Variable name')?></th>
                    <th><?php echo $t->_('Answer')?></th>
                </tr>
                <tr>
                    <td class="text-center">
                        <div style="display: none;">
                            <input type="number" class="small-text answer_sl" name="answers[sl][]" value="1">
                        </div>
                        <input type="text" class="answer_variable" name="answers[variable][]" value="" placeholder="Tên biến">
                    </td>
                    <td style="padding: 5px; vertical-align: top;">
                        <input type="text" class="form-control answer_text" name="answers[answer][]" value="" placeholder="<?php echo $t->_('Correct answer')?>">
                    </td>
                </tr>
            </table>
            <div class="btn-group-xs">
                <button type="button" class="btn btn-danger btn-flat" onclick="return bookAnswer.answerRemove(this);"><i class="fa fa-times"></i> | <?php echo $t->_('Delete answer')?></button>
                <button type="button" class="btn btn-default btn-flat" style="cursor: move;"><i class="fa fa-arrows-alt"></i> | <?php echo $t->_('Move')?></button>
            </div>
        </li>
    <?php endif; ?>
</ul>
<button type="button" class="btn btn-primary btn-flat btn-xs" onclick="return bookAnswer.addAnswer(this);"><i class="fa fa-plus"></i> | <?php echo $t->_('Add more answer')?></button>