<div class="col-xs-12">
    <?php echo $this->getContent(); ?>
</div>
<form action="/admin/questions/saveSummary" method="post" id="question_form">
    <div class="col-xs-12 no-padding">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Tạo câu hỏi cho bài trắc nghiệm tổng hợp (<?php echo $section->name ?>)</h3>
            </div>
            <div class="box-body no-padding">
                <table class="table table-striped">
                    <tr>
                        <th>Loại câu hỏi</th>
                        <th class="text-right">Số câu hỏi hiện có</th>
                        <th class="text-right">Số câu hỏi lấy ngẫu nhiên</th>
                    </tr>
                    <?php foreach($questions as $chapterId => $chapter):?>
                        <tr>
                            <td colspan="3" class="bg-light-blue"><span class="fa fa-ellipsis-v"></span> <?php echo $chapter['name'] ?></td>
                        </tr>
                        <?php foreach($chapter['sections'] as $sectionId => $section):?>
                            <tr>
                                <td colspan="3" class="bg-gray">
                                    <span class="fa fa-ellipsis-h"></span> <strong><?php echo $section['name'] ?></strong>
                                    <div class="progress xs" style="height:2px;">
                                        <div class="progress-bar progress-bar-danger" style="width: 100%"></div>
                                    </div>
                                </td>
                            </tr>
                            <?php foreach($section['questions'] as $type => $question):?>
                                <tr>
                                    <td><span class="fa fa-ellipsis-h"></span> <span class="fa fa-ellipsis-h"></span>  <?php echo $type ?></td>
                                    <td class="text-right"><?php echo count($question) ?></td>
                                    <td class="text-right"><?php echo $this->tag->numericField(array("number[$chapterId][$sectionId][$type]", "size" => "3", "min" => "0", "max" => count($question), "value" => count($question))) ?></td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php echo $this->tag->hiddenField("id") ?>
            <?php echo $this->tag->hiddenField("section_id") ?>
            <?php echo $this->tag->hiddenField("section_id") ?>
            <?php echo $this->tag->hiddenField( array("questionIds",'value' => json_encode($questions))) ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <button type="button" onclick="return bookTool.resetForm(this,'question');" class="btn btn-small btn-warning btn-flat"><i class="fa fa-refresh"></i> | <?php echo $t->_('Cancel') ?></button>
                    <button type="submit" class="btn btn-small btn-primary btn-flat"><i class="fa fa-save"></i> | <?php echo $t->_('Save') ?></button>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(function(){
        $("#question_form").submit(function(ev) {
            $.ajax({
                url: '/admin/questions/saveSummary',
                data:$('#question_form').serialize(),
                type: 'post',
                dataType: 'json',
                success: function(result) {
                    console.log(result);
                    if(result.error) {
                        alertify.error(result.msg);
                    } else {
                        alertify.success(result.msg);
                    }
                    //window.location.reload();
                },
                error: function(jqXHR){
                    alertify.error("Error: Loading data");
                }
            });
            ev.preventDefault();
            return false;
        });
    });
</script>