<div class="row pad">
    <div class="box-header">
        <div class="box-title">
            <?php echo $section->breadcrumb['book_name'] ?> > <?php echo $section->breadcrumb['chapter_name'] ?> > <?php echo $section->name ?> ><strong><?php echo $this->tag->getValue('_id')==''?$t->_('Create question'):$t->_('Edit question')?></strong>
        </div>
    </div>
</div>
<form action="#" method="post" id="question_form">
    <div class="col-xs-12 no-padding">

            <div class="box-body">
                <div class="row">
                    <div class="col-lg-7 col-md-7 col-xs-12">
                        <div class="form-group">
                            <label for="question"><?php echo $t->_('Question content')?></label>
                            <?php echo $this->tag->textArea(array("question", "rows"=>6, 'class' => 'form-control')) ?>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-5 col-xs-12 no-padding">
                        <div class="col-xs-12 no-padding">
                            <div class="form-group-sm col-xs-4">
                                <label for="status"><?php echo $t->_('Status')?></label>
                                <?php echo $this->tag->selectStatic(array("status", 'class' => 'form-control'), array("1" => 'YES', "0" => 'NO')) ?>
                            </div>
                            <div class="form-group-sm col-xs-4 no-padding" data-toggle="tooltip" data-placement="bottom" title="Hệ thống sẽ tự động tăng số thứ tự này khi để mặc định là 0">
                                <label for="order"><?php echo $t->_('Order')?></label>
                                <div class="input-group input-group-sm col-xs-12">
                                    <?php echo $this->tag->textField(array("order", "size" => 30, 'class' => 'form-control')) ?>
                                    <span class="input-group-addon">
                                    <i class="fa fa-sort-numeric-asc"></i>
                                </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="correct_msg"><?php echo $t->_('Correct Msg')?></label>
                            <?php echo $this->tag->textArea(array("correct_msg", "rows"=>3, 'class' => 'ckeditor form-control')) ?>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="incorrect_msg"><?php echo $t->_('InCorrect Msg')?></label>
                            <?php echo $this->tag->textArea(array("incorrect_msg", "rows"=>3, 'class' => 'ckeditor form-control')) ?>
                        </div>
                        <div class="form-group col-xs-12">
                            <label for="allow_translate"><?php echo $t->_('Allow translate')?></label>
                            <div class="input-group ">
                                <span class="input-group-addon"><i class="fa fa-text-width"></i> Click <?php echo $this->tag->checkField(array("allow_translate", $question->allow_translate?'checked':'','value'=>1)) ?> to translate</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group col-xs-12" id="question_translate_content" style="display: <?php echo $question->allow_translate?'block':'none'; ?>">
                        <div class="box box-info bg-light-gray">
                            <div class="box-header">
                                <div class="box-title">
                                    <i class="fa fa-text-width"></i> <?php echo $t->_('Question translate')?>
                                </div>
                            </div>
                            <div class="box-body">
                                <div class="row">
                                    <div class="form-group col-sm-12">
                                        <label for="question_translate"><?php echo $t->_('Question content (Translate)')?></label>
                                        <?php echo $this->tag->textArea(array("translates[question]","value"=>$question->translates['question'], "id"=>"translates_question", "rows"=>10, 'class' => 'form-control')) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="box box-info">
                            <div class="box-header">
                                <div class="box-title">
                                    <?php echo $t->_('Answers')?> <small>(<?php echo $t->_('Required')?>)</small>
                                    <div class="box-tools pull-right col-xs-4 no-padding">
                                        <div class="input-group pull-right">
                                            <?php if($type == 'GROUP'): ?>
                                                <span class="input-group-addon"><i class="fa fa-qrcode"></i> <?php echo $t->_('Question group')?></span>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="box-body">
                                <div id="question_answer_groups">
                                    <?php $this->partial('questions/types/'.strtolower($type), array('answers' => $question->answers, 'question' => $question)); ?>
                                </div>
                            </div>
                            <div class="box-footer text-right" id="answer_groups" style="display:<?php echo $type == 'GROUP'?'block':'none'?>">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->tag->hiddenField("_id") ?>
            <?php echo $this->tag->hiddenField("section_id") ?>
            <?php echo $this->tag->hiddenField("type") ?>
            <div class="box-footer text-right">
                <div class="btn-group-xs">
                    <button type="button" onclick="return bookTool.resetForm(this,'question');" class="btn btn-small btn-flat btn-warning"><i class="fa fa-refresh"></i> | <?php echo $t->_('Cancel')?></button>
                    <button type="button" onclick="return bookTool.saveQuestion(this);" class="btn btn-small btn-flat btn-primary"><i class="fa fa-save"></i> | <?php echo $t->_('Save')?></button>
                    <button type="button" onclick="return bookTool.saveQuestionAndContinue(this,'<?php echo $type ?>');" class="btn btn-small btn-flat btn-info"><i class="fa fa-save"></i> | Lưu và tạo mới</button>
                </div>
            </div>
        </div>
</form>
<style>
    .cke_editable_inline {
        border: 1px solid #cccccc;
        min-height: 90px;
        background: #ffffff;
    }
</style>
<script>
    var question = CKEDITOR.replace('question');
    var correct_msg = CKEDITOR.inline('correct_msg');
    var incorrect_msg = CKEDITOR.inline('incorrect_msg');
    CKFinder.setupCKEditor( question, '/js/ckfinder/' );
    var question_translate = CKEDITOR.replace('translates_question');
    CKFinder.setupCKEditor( question_translate, '/js/ckfinder/' );
    question.on( 'change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#question').html(evt.editor.getData());
    });
    question_translate.on('change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#translates_question').html(evt.editor.getData());
    });
    correct_msg.on('change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#correct_msg').html(evt.editor.getData());
    });
    incorrect_msg.on('change', function( evt ) {
        // getData() returns CKEditor's HTML content.
        $('#incorrect_msg').html(evt.editor.getData());
    });
    var edit_answer = CKEDITOR.replace('edit_answer');
    function resetiCheck() {
        $('#allow_translate').change(function() {
            if ($(this).is(':checked')) {
                $("#question_translate_content").show();
            } else {
                $("#question_translate_content").hide();
            }
        });
    }
    function addmoregroup(myself) {
        var content = $("#question_answer_groups .question_answer_group:first-child").html();
        $("#question_answer_groups").append(content);
    }

    var elementPopup = '';
    function openModal(event,myself) {
        event.preventDefault();
        var checkAllowHtml = $(myself).parent().parent().find('.answer_html');
        elementPopup = $(myself).parent().parent().find('.answer_text');
        var value = elementPopup.val();
        $('#edit_answer').val(value);
        edit_answer.setData(value);
        if(checkAllowHtml.prop('checked')) {
            $('#editorModal').modal('show');
        } else {
            alertify.error("You must to click the checkbox allow html.");
        }
        return false;
    };
    function applyDataModal(myself) {
        elementPopup.val(edit_answer.getData());
        $('#editorModal').modal('hide');
    };
    $(function(){
        resetiCheck();
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>
<div class="modal fade" id="editorModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?php echo $t->_('Edit answer') ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->tag->textArea(array("edit_answer", "rows"=>10, 'class' => 'form-control')) ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $t->_('Cancel') ?></button>
                <button type="button" class="btn btn-primary" onclick="applyDataModal(this);"><?php echo $t->_('Done') ?></button>
            </div>
        </div>
    </div>
</div>
