<div class="table-responsive" id="chapter_container">
    <!-- THE MESSAGES -->
    <table class="table table-mailbox table-bordered table-hover" id="sortable">
        <tr class="unread">
            <td  class="text-center small-col">STT</td>
            <td style="max-width:50%" class="question"><?php echo $t->_('Question content') ?></td>
            <td class="text-right"><?php echo $t->_('Question type') ?></td>
            <td style="width: 10%" class="text-center"><?php echo $t->_('Tools') ?></td>
        </tr>
        <?php foreach($questions as $question):?>
            <tr class="order" data-order="<?php echo $question->order ?>" data-id="<?php echo $question->getId() ?>">
                <td class="small-col text-center"><?php echo $question->order ?></td>
                <td style="white-space:pre-wrap; max-width: 50%;"><span class="math"><?php echo Helper::limitString($question->question,300) ?></span></td>
                <td class="text-right"><?php echo $question->type ?></td>
                <td class="text-center">
                    <button class="btn btn-xs btn-flat btn-warning" onclick="return bookTool.editQuestion(this, '<?php echo $question->getId() ?>',null,'<?php echo $question->section['id'] ?>');"><i class="fa fa-pencil"></i></button>
                    <button class="btn btn-xs btn-flat btn-danger" onclick="return bookTool.deleteQuestion(this, '<?php echo $question->getId()?>');"><i class="fa fa-trash-o"></i></button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div><!-- /.table-responsive -->