<?php echo $this->getContent() ?>
<div class="col-xs-12 no-padding">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <div class="row">
                    <div class="col-xs-3">Danh sách quyền</div>
                    <div class="col-xs-3 text-right">Quản lý chuyên đề</div>
                    <div class="col-xs-3 text-right">Quản lý sách</div>
                    <div class="col-xs-3 text-right">Quản lý người dùng</div>
                </div>
            </h3>
        </div>
        <div class="panel-body">
            <small><i class="text-danger">Quyền nào được cho phép dùng chức năng nào thì sẽ chỉ được phép dùng chức năng đó.</i></small>
        </div>
        <?php echo $this->tag->form("admin/permissions/save") ?>
        <ul class="list-group">
            <?php foreach ($roles as $index => $role): ?>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-xs-3">
                            <?php echo $role->name ?>
                            <input type="text" name="roles[]" value="<?php echo $role->getId() ?>">
                        </div>
                        <div class="col-xs-3 text-right"><input data-size="mini" type="checkbox" name="topics[]" data-toggle="toggle"></div>
                        <div class="col-xs-3 text-right"><input data-size="mini" type="checkbox" name="books[]"checked data-toggle="toggle"></div>
                        <div class="col-xs-3 text-right"><input data-size="mini" type="checkbox" name="users[]"data-toggle="toggle"></div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
        <div class="panel-footer text-right">
            <div class="btn-group-xs">
                <button type="submit" class="btn btn-xs btn-primary btn-flat"><i class="fa fa-save"></i> Lưu</button>
            </div>
        </div>
        <?php echo $this->tag->endForm() ?>
    </div>


</div>