<div class="callout callout-danger">
    <h4>Cảnh báo!</h4>
    <p>Hiện tại có <?php echo count($books) ?> cuốn sách đang dùng chuyên đề này. Xin vui lòng kiểm tra chắc chắn trước khi xóa.</p>
    <p>Nếu bạn chắc chắn xóa thì hệ thống sẽ xóa chuyên đề này trong toàn bố số sách bên dưới.</p>
</div>
<div class="col-xs-12 no-padding">
    <table class="table table-striped table-bordered table-responsive table-hover" align="center">
        <thead>
        <tr>
            <th  class="text-center small-col">STT</th>
            <th  class="text-left" ><?php echo $t->_('Book name') ?></th>
            <th class="text-center" width="10%">Trạng thái</th>
            <th class="text-center" width="10%">Miễn phí</th>
            <th class="text-center" width="10%">Test</th>
            <th class="text-center" width="20%">Ngày tạo</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($books as $index => $book): ?>
            <tr>
                <td class="small-col text-center"><?php echo $index+1; ?></td>
                <td class="text-center"><?php echo $book->name; ?></td>
                <td class="text-center">
                    <?php echo Helper::getIconStatus($book->status) ?>
                </td>
                <td class="text-center">
                    <?php echo Helper::getIconStatus($book->free, 0) ?>
                </td>
                <td class="text-center">
                    <?php echo Helper::getIconStatus($book->test, 0) ?>
                </td>
                <td class="text-center"><?php echo Helper::formatDate($book->created_at) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?php echo $this->tag->form("") ?>
    <button type="submit" class="btn btn-xs btn-danger btn-flat"><i class="fa fa-times"></i> Xóa tất cả</button>
    <?php echo $this->tag->endForm() ?>
</div>