<?php echo $this->getContent() ?>
<div class="col-xs-12">
    <div class="page-header">
        <div class="text-left col-xs-4 no-padding">
            <form method="get">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" id="txt_search" name="search" value="<?php echo $search ?>" placeholder="<?php echo $t->_('Enter name for search',array('name' => 'Chuyên đề'))?>">
                    <span class="input-group-btn">
                        <button id="btn_search" class="btn btn-primary btn-flat" type="submit"><?php echo $t->_('Search') ?></button>
                    </span>
                </div>
            </form>
        </div>
        <div class="text-right">
            <div class="btn-group-xs">
                <?php echo $this->tag->linkTo(array("admin/category/new", "<i class='fa fa-plus-circle'></i> | {$t->_('Create Topic')}", "class"=>"btn btn-small btn-primary btn-flat")); ?>
            </div>
        </div>
    </div>
    <table class="table table-striped table-bordered table-responsive table-hover" id="sortable" align="center">
        <thead>
        <tr>
<!--            <th class="text-center" style="width:10px">
                <div class="fa fa-save disabled" style="color:gray;" id="save_order" onclick="saveOrder(this);"></div>
            </th>-->
            <th  class="text-center small-col">STT</th>
            <th  class="text-left" ><?php echo $t->_('Topic name') ?></th>
            <th  class="text-right" width="15%"><?php echo $t->_('Number book display') ?></th>
            <th  class="text-center" width="10%"><?php echo $t->_('Avatar') ?></th>
            <th  class="text-center" width="10%"><?php echo $t->_('Status') ?></th>
            <th  class="text-center" width="10%"><?php echo $t->_('Created') ?></th>
            <th  class="text-center" style="width:145px;"><?php echo $t->_('Tools') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($pager as $index => $category) { ?>
            <tr data-order="<?php echo $category->order ?>" data-id="<?php echo $category->getId() ?>">
                <!--<td class="text-center" style="cursor:move"><i class="fa fa-ellipsis-v"></i><i class="fa fa-ellipsis-v"></i></td>-->
                <td class="small-col text-center"><?php echo $category->order ?></td>
                <td>
                    <?php echo $this->tag->linkTo(array("admin/category/edit/" . $category->getId(), $category->name)); ?>
                </td>
                <td class="text-right"><?php echo $category->number_book_display ?></td>
                <td class="text-center"><img  style="width:50px" class="img-responsive img-rounded img-thumbnail" src="<?php echo $category->image ?>"/></td>
                <td class="text-center">
                    <?php echo Helper::getIconStatus($category->status) ?>
                </td>
                <td class="text-center"><?php echo Helper::formatDate($category->created_at, Helper::DATE_FORMAT_FULL) ?></td>
                <td style="text-align: right">
                    <div class="btn-group-xs">
                        <?php echo $this->tag->linkTo(array("admin/category/edit/" . $category->getId(), $t->_('Edit') .' | <span class="fa fa-edit"></span>', 'class' => 'btn btn-small btn-sm btn-warning btn-flat')); ?>
                        <?php echo $this->tag->linkTo(array("admin/category/delete/" . $category->getId(), $t->_('Delete') .'| <span class="fa fa-trash-o"></span>', 'class' => 'btn btn-small btn-sm btn-danger btn-flat','onclick' => 'return confirm("Do you want to delete this category?");')); ?>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="dataTables_paginate paging_bootstrap">
        <?php echo $pager->getLayout() ?>
    </div>
</div>
<script>
    var categoryIds;
    $(function(){
        $( "#sortable tbody" ).sortable({
            placeholder: "ui-state-highlight",
            axis: 'y',
            update: function (event, ui) {
                categoryIds = $.map($(this).find('tr'),function(obj, index) {
                    return {
                        id: $(obj).data('id'),
                        order: parseInt(index+1)
                    };
                });
                $('#save_order').removeClass('disabled');
                $('#save_order').css({color:'#f4543c',cursor:'pointer'});
            }
        }).disableSelection();
    });
    function saveOrder(myself) {
        $.ajax({
            type: "POST",
            url: "/admin/category/saveCategoryOrder",
            data: {categoryIds:categoryIds},
            dataType: 'json',
            beforeSend: function () {
            },
            success: function (results) {
                if(results.error == true) {
                    alertify.error("Error: Save failed");
                } else {
                    alertify.success("Saved successfully.");
                }
                $('#save_order').addClass('disabled');
                $('#save_order').css({color:'gray',cursor:'normal'});
            },
            error: function () {
                $('#save_order').addClass('disabled');
                alertify.error("Error: Save failed");
            }
        });
    }
</script>